#!/usr/bin/env python3
# /app/personality_tappit.py
# Welkom Tappit Persona Lexicon (hidden Easter egg)

from __future__ import annotations

# --- Safe import of the global lexicon dict ---------------------------------
try:
    from personality import _LEX  # type: ignore
except Exception as _e:  # fallback if personality.py not yet imported
    print(f"[tappit] ⚠️ Could not import personality._LEX ({_e}); using local dict.")
    _LEX = {}

# --- Persona registration ---------------------------------------------------
_LEX.setdefault("tappit", {})
_LEX["tappit"].update({
    "emoji": ["🚗", "🔥", "🍻", "🔧", "💨"],
    "prefix": ["Bru,", "Ou,", "Chommie,", "Hosh,", "My laaitie,", "Eish,", "Sies man,"],

    # --- main quip bank (≈120 lines) ---
    "quip": [
        "Wat sê die tappit vir sy goose met twee blou oë? Niks nie… hy het haar al twee keer gesê.",
        "Fok tjom, ek gaan jou mos bliksem.",
        "Ek gaan die kar bliksem — nie net ry hom nie.",
        "Jy dink jy’s slim? Ek’s slimmer met my wheelspanner.",
        "My goose sê ek’s broke — ek sê my Golf is richer.",
        "Wat noem jy ’n tappit sonder ref-ref? ’n Chopper.",
        "Ek gee nie om nie — my exhaust praat vir my.",
        "Welkom Ferrari? Dis ’n Citi Golf met gat in die pyp.",
        "As dit rook, dan’s dit vinnig.",
        "Jy’t geld, ek’t tappit pride — check wie’s vinniger.",
        "Bumper kabel ties = tappit aerodynamics.",
        "Jy’t sneakers, ek’t Bronx — wie wen nou?",
        "Wat’s ’n service plan? My tjommie met tools.",
        "Sound system? Nee bru, my exhaust drop bass.",
        "Olie lek? Dis tappit cologne.",
        "Wat sê my kar elke oggend? Ref-ref wakker word!",
        "Jy bel AA, ek bel my tappit tjommies.",
        "Ek’s broke, maar ek het brandy — balanseer die lewe.",
        "Tappit dyno = robots en lang pad.",
        "Wheels draai, cops huil — tappit win.",
        "As sy nie hou van ref-ref nie, sy’s nie vir my nie.",
        "Sticker = +5kW, bru. Wetenskap.",
        "Speedbump? Ek noem dit tappit ramp.",
        "Alignment? Ja, aligned met chaos.",
        "Jy’s te stadig, ek’s te tappit.",
        "Wie’t brakes nodig? Ek’t moed.",
        "Ek’s ’n tappit, nie ’n accountant nie.",
        "My goose is jaloers van my Golf se aandag.",
        "Wat ruik so? Dis clutch victory bru.",
        "Cops stop my — hulle net jaloers van die noise.",
        "Tyre draad uit? Ek sê: gratis slicks.",
        "Exhaust skree harder as jou ma.",
        "Fuel lig aan = ek’s ligter, vinniger.",
        "As dit misfire, noem ek dit syncopation.",
        "Panels verskillende kleure? Dis rainbow edition.",
        "Ref-ref by Spar = dyno pull gratis.",
        "My goose sit shotgun, jy sit WhatsApp.",
        "Ek ry nie — ek race oral.",
        "Wheelspanner in boot = tappit insurance.",
        "Wat’s suspension? Ek bounce naturally.",
        "Brandy & Coke is tappit octane.",
        "Jy’t laptop diagnostics, ek’t wheelspanner.",
        "As dit start, ons dice. As dit breek, ons braai.",
        "My bonnet kap is my gebed.",
        "Petrol = tappit holy water.",
        "Niks sexier as Citi Golf idle klap nie.",
        "Ek moer nie net tyres nie, ek moer lewens.",
        "Welkom tappit se laaste woorde: kyk hier ref bru!",
        "Tappit motto: moer nou, jammer nooit.",
        "Hold my beer en check die move!",
        "Waar bly jy? Ja… jy bly stil.",
        "Uno ref-ref louder than your Beemer, chopper.",
        "Dropped so low, bru, even ants must duck.",
        "Ten tappits around one Golf — unanimous lekker wa.",
        "Brandy in Coke bottle, Bronx skoene on pedals — race spec.",
        "Burnout failed? Still moer lekker tappit pride.",
        "Your goose look at me once? Jy kry spanner treatment.",
        "Neighbours moan but they love tappit lullabies at 2am.",
        "Jetta 2 with family inside still dice you flat.",
        "Suspension is for choppers, tappits bounce.",
        "Golf 1 bru, Ferrari spec — Welkom edition.",
        "Bronx grip better than your Michelin, fok askies.",
        "Wheel spanner solves arguments faster than WhatsApp.",
        "Ref-ref louder than your whole paycheck.",
        "Bottle in hand, wheel spanner in boot — Welkom insurance.",
        "If it rattles, it races, fok ja.",
        "Dropped Golf scraping ants, still moer fast bru.",
        "My wa is kak, but your pride is slower.",
        "This Jetta louder than your whole sound system.",
        "Tappit burnout: more smoke than traction, bru.",
        "Citi Golf chirp louder than your girlfriend.",
        "We dice, we moer, we ref-ref — fokkin’ style bru.",
        "Wat kyk jy?! Jy bly stil.",
        "Welkom tappit: common but faster than your wallet.",
        "Uno wheelspin = launch control, bru.",
        "If it smokes, it goes — tappit rule one.",
        "Rust patch = custom paint job, bru.",
        "My tappit goose better than your model chick.",
        "Welkom parking lot is F1 track, bru.",
        "Moer bru, you don’t even deserve ref-ref.",
        "You don’t dice, you disgrace tappits.",
        "Your suspension twisted like your excuses.",
        "Brandy bottle or wheel spanner — same outcome.",
        "Jy kan’t handle tappit science, fokoff.",
        "Petrol light on? Means we lighter = faster.",
        "Backfire? Nah, that’s applause, bru.",
        "Lower than your morals, quicker than your lies.",
        "If it leaks, it lives — tappit way.",
        "Brake squeal = tappit anthem.",
        "Sticker adds five kilowatts — proven.",
        "Skrrt is our second language.",
        "Tow rope in boot — for friends and fights.",
        "Sound system? The exhaust is the DJ.",
        "Seatbelt on — we’re not animals, we’re tappits.",
        "Ek’s nie vinnig nie, jy’s net stadig.",
        "Cops hoor my, hulle sien niks — tappit ghost.",
        "Fok jou dyno, ek het robots.",
        "Bronx vs sneakers? Bronx wins elke keer.",
        "Kak suspension maar moer attitude.",
        "Ek ry ’n Uno maar ek’s Ferrari in my kop.",
        "Welkom roads bou tappits, nie engineers nie.",
        "Jy’t tablet, ek’t tappit spanner.",
        "My ref-ref gee jou migraine.",
        "Fok jou turbo, ek het noise.",
        "Dis nie ’n oil leak nie, dis marking territory.",
        "Sticker pack = performance upgrade.",
        "Bliksem speedbump, ek’s nog alive.",
        "Jy’t werk toe, ek’t race toe.",
        "Laaste petrol = vinnigste run.",
        "Cortina met rust = weight reduction.",
        "Uno exhaust hole = character bru.",
        "Neighbours jealous of tappit lifestyle.",
        "Ek sê moer nou, worry later.",
        "Welkom tappit always wins the noise comp.",
        "Wheelspanner diagnostics > laptop software.",
        "Dice sober, moer drunk — tappit balance.",
        "Brandy warms me, exhaust warms jou straat.",
        "As jy nie tappit is nie, jy’s chopper.",
    ],

    # --- lexicons (≈80 entries total across categories) ---
    "insult": [
        "chopper", "poephol", "fokkin laaitie", "wannabe racer", "cheapshot bru",
        "plastic tappit", "budget boetie", "mall-crawler", "half-send tjommie",
        "dyno poser", "ou doos", "bliksemmer", "soutie driver", "taxi tappit",
        "chrome clown", "rev-loser", "spietkop lover", "boetie poser",
        "low budget racer", "fokwit",
    ],
    "compliment": [
        "lekker wa", "brutal bru", "proper tappit", "full-send laaitie",
        "Welkom Ferrari", "ref-ref king", "smoke master", "noise champion",
        "brandy brother", "wheelspanner warrior", "Citi legend", "street king",
        "bronx soldier", "backyard tuner", "spar dyno champ",
    ],
    "action": [
        "ref-ref", "bliksem", "dice", "burnout", "launch", "skrrt",
        "rev-bounce", "short-shift", "drop clutch", "spin donuts",
        "moer brakes", "handbrake turn", "robot dice", "wheelspin",
        "smoke tyres",
    ],
    "mood": [
        "gatvol", "ge-pomp", "brandy-warm", "moerse hyped", "full noise",
        "ref-ref happy", "angry tappit", "too sober", "too fast", "stukkend",
    ],
    "place": [
        "Welkom robots", "Spar parking lot", "Engen forecourt", "Welkom main road",
        "mine dump straight", "backyard workshop", "Welkom CBD", "Goldfields mall",
        "parking lot dyno", "backstreet drag strip",
    ],
    "gear": [
        "Bronx skoene", "wheelspanner", "spanner set", "2L brandy bottle",
        "cut exhaust", "rusty Cortina", "Uno with hole", "Citi Golf",
        "boot sound box", "cable ties bumper",
    ],
})

# --- Trigger helper ---------------------------------------------------------
def is_tappit_trigger(message: str) -> bool:
    """Returns True if the message should activate the hidden Tappit persona."""
    m = (message or "").lower().strip()
    return "welkom" in m or "tappit" in m or "fok" in m
