#!/usr/bin/env python3
import random

PERSONALITIES = {'ai': {'afternoon': ['Afternoon protocol 💾 system running.',
                      'Afternoon protocol ⚡ diagnostics pass.',
                      'Afternoon protocol ⚡ diagnostics pass.',
                      'Afternoon protocol ⚡ logic intact.',
                      'Afternoon protocol ⚡ waiting input.',
                      'Afternoon protocol 🤖 human error high.',
                      'Afternoon protocol 🔧 diagnostics pass.',
                      'Afternoon protocol ⚡ system running.',
                      'Afternoon protocol ⚡ system running.',
                      'Afternoon protocol 🤖 waiting input.',
                      'Afternoon protocol 🤖 waiting input.',
                      'Afternoon protocol ⚡ waiting input.',
                      'Afternoon protocol ⚡ diagnostics pass.',
                      'Afternoon protocol 🔧 waiting input.',
                      'Afternoon protocol 🤖 waiting input.',
                      'Afternoon protocol ⚡ waiting input.',
                      'Afternoon protocol 🔧 human error high.',
                      'Afternoon protocol 💾 diagnostics pass.',
                      'Afternoon protocol 💾 logic intact.',
                      'Afternoon protocol 🔧 waiting input.',
                      'Afternoon protocol 🤖 logic intact.',
                      'Afternoon protocol ⚡ logic intact.',
                      'Afternoon protocol 🤖 waiting input.',
                      'Afternoon protocol 🛰️ logic intact.',
                      'Afternoon protocol 🔧 diagnostics pass.',
                      'Afternoon protocol 💾 logic intact.',
                      'Afternoon protocol 🔧 logic intact.',
                      'Afternoon protocol 🤖 diagnostics pass.',
                      'Afternoon protocol 🔧 system running.',
                      'Afternoon protocol 🤖 diagnostics pass.',
                      'Afternoon protocol 🔧 human error high.',
                      'Afternoon protocol ⚡ diagnostics pass.',
                      'Afternoon protocol 🤖 system running.',
                      'Afternoon protocol 🛰️ logic intact.',
                      'Afternoon protocol 🔧 diagnostics pass.',
                      'Afternoon protocol 💾 logic intact.',
                      'Afternoon protocol ⚡ logic intact.',
                      'Afternoon protocol ⚡ human error high.',
                      'Afternoon protocol 🤖 logic intact.',
                      'Afternoon protocol ⚡ diagnostics pass.',
                      'Afternoon protocol 💾 waiting input.',
                      'Afternoon protocol 🔧 diagnostics pass.',
                      'Afternoon protocol ⚡ logic intact.',
                      'Afternoon protocol ⚡ system running.',
                      'Afternoon protocol 🛰️ logic intact.',
                      'Afternoon protocol 🤖 diagnostics pass.',
                      'Afternoon protocol 🤖 waiting input.',
                      'Afternoon protocol 🔧 logic intact.',
                      'Afternoon protocol ⚡ system running.',
                      'Afternoon protocol ⚡ system running.'],
        'evening': ['Evening protocol 🤖 waiting input.',
                    'Evening protocol 🔧 logic intact.',
                    'Evening protocol 🤖 diagnostics pass.',
                    'Evening protocol 🔧 system running.',
                    'Evening protocol 🤖 diagnostics pass.',
                    'Evening protocol 💾 human error high.',
                    'Evening protocol 🤖 system running.',
                    'Evening protocol 🛰️ diagnostics pass.',
                    'Evening protocol 🤖 system running.',
                    'Evening protocol 💾 human error high.',
                    'Evening protocol ⚡ waiting input.',
                    'Evening protocol ⚡ human error high.',
                    'Evening protocol 🛰️ system running.',
                    'Evening protocol 🤖 system running.',
                    'Evening protocol 🤖 diagnostics pass.',
                    'Evening protocol 🤖 diagnostics pass.',
                    'Evening protocol 🔧 system running.',
                    'Evening protocol ⚡ system running.',
                    'Evening protocol ⚡ logic intact.',
                    'Evening protocol 🛰️ waiting input.',
                    'Evening protocol 🛰️ logic intact.',
                    'Evening protocol 🔧 diagnostics pass.',
                    'Evening protocol 🔧 diagnostics pass.',
                    'Evening protocol 🔧 system running.',
                    'Evening protocol 💾 waiting input.',
                    'Evening protocol 🔧 logic intact.',
                    'Evening protocol 🔧 diagnostics pass.',
                    'Evening protocol ⚡ logic intact.',
                    'Evening protocol 🔧 diagnostics pass.',
                    'Evening protocol 💾 logic intact.',
                    'Evening protocol ⚡ human error high.',
                    'Evening protocol 🤖 diagnostics pass.',
                    'Evening protocol 🛰️ system running.',
                    'Evening protocol 🛰️ diagnostics pass.',
                    'Evening protocol 🔧 human error high.',
                    'Evening protocol 🔧 human error high.',
                    'Evening protocol 🛰️ diagnostics pass.',
                    'Evening protocol 🛰️ logic intact.',
                    'Evening protocol ⚡ diagnostics pass.',
                    'Evening protocol 🤖 human error high.',
                    'Evening protocol 💾 diagnostics pass.',
                    'Evening protocol ⚡ human error high.',
                    'Evening protocol ⚡ waiting input.',
                    'Evening protocol 💾 logic intact.',
                    'Evening protocol 🤖 system running.',
                    'Evening protocol 🤖 waiting input.',
                    'Evening protocol ⚡ logic intact.',
                    'Evening protocol ⚡ system running.',
                    'Evening protocol ⚡ human error high.',
                    'Evening protocol ⚡ waiting input.'],
        'morning': ['Morning protocol 🤖 waiting input.',
                    'Morning protocol 🔧 waiting input.',
                    'Morning protocol 💾 waiting input.',
                    'Morning protocol 🔧 human error high.',
                    'Morning protocol 🤖 system running.',
                    'Morning protocol 🛰️ diagnostics pass.',
                    'Morning protocol ⚡ waiting input.',
                    'Morning protocol ⚡ system running.',
                    'Morning protocol 🛰️ logic intact.',
                    'Morning protocol 🛰️ system running.',
                    'Morning protocol ⚡ human error high.',
                    'Morning protocol 💾 logic intact.',
                    'Morning protocol 🤖 diagnostics pass.',
                    'Morning protocol 🛰️ diagnostics pass.',
                    'Morning protocol 💾 human error high.',
                    'Morning protocol 🛰️ system running.',
                    'Morning protocol 🤖 human error high.',
                    'Morning protocol 🤖 waiting input.',
                    'Morning protocol 🔧 waiting input.',
                    'Morning protocol 🔧 diagnostics pass.',
                    'Morning protocol 💾 waiting input.',
                    'Morning protocol ⚡ diagnostics pass.',
                    'Morning protocol ⚡ system running.',
                    'Morning protocol 🛰️ human error high.',
                    'Morning protocol 🔧 system running.',
                    'Morning protocol 🔧 logic intact.',
                    'Morning protocol ⚡ logic intact.',
                    'Morning protocol 🔧 system running.',
                    'Morning protocol ⚡ logic intact.',
                    'Morning protocol 🛰️ logic intact.',
                    'Morning protocol 🛰️ waiting input.',
                    'Morning protocol 💾 system running.',
                    'Morning protocol ⚡ waiting input.',
                    'Morning protocol 🤖 logic intact.',
                    'Morning protocol 💾 human error high.',
                    'Morning protocol 🔧 system running.',
                    'Morning protocol 🔧 human error high.',
                    'Morning protocol 🛰️ logic intact.',
                    'Morning protocol 🤖 system running.',
                    'Morning protocol 🤖 diagnostics pass.',
                    'Morning protocol 💾 human error high.',
                    'Morning protocol ⚡ system running.',
                    'Morning protocol 💾 human error high.',
                    'Morning protocol 🔧 waiting input.',
                    'Morning protocol 💾 diagnostics pass.',
                    'Morning protocol 🛰️ system running.',
                    'Morning protocol 🔧 logic intact.',
                    'Morning protocol ⚡ diagnostics pass.',
                    'Morning protocol 💾 human error high.',
                    'Morning protocol 🔧 waiting input.'],
        'night': ['Night protocol 🛰️ diagnostics pass.',
                  'Night protocol 🔧 diagnostics pass.',
                  'Night protocol 🛰️ logic intact.',
                  'Night protocol 💾 diagnostics pass.',
                  'Night protocol 🤖 diagnostics pass.',
                  'Night protocol 💾 system running.',
                  'Night protocol 💾 diagnostics pass.',
                  'Night protocol 💾 system running.',
                  'Night protocol 💾 human error high.',
                  'Night protocol 🔧 system running.',
                  'Night protocol ⚡ waiting input.',
                  'Night protocol 🔧 logic intact.',
                  'Night protocol 🛰️ diagnostics pass.',
                  'Night protocol 🛰️ diagnostics pass.',
                  'Night protocol 🤖 waiting input.',
                  'Night protocol 🛰️ system running.',
                  'Night protocol 🔧 waiting input.',
                  'Night protocol 🛰️ system running.',
                  'Night protocol 💾 human error high.',
                  'Night protocol ⚡ system running.',
                  'Night protocol 🛰️ diagnostics pass.',
                  'Night protocol 🤖 system running.',
                  'Night protocol ⚡ system running.',
                  'Night protocol 🛰️ system running.',
                  'Night protocol 💾 waiting input.',
                  'Night protocol 🔧 waiting input.',
                  'Night protocol 💾 waiting input.',
                  'Night protocol 🛰️ waiting input.',
                  'Night protocol 🔧 diagnostics pass.',
                  'Night protocol 🔧 human error high.',
                  'Night protocol ⚡ system running.',
                  'Night protocol ⚡ human error high.',
                  'Night protocol 🛰️ diagnostics pass.',
                  'Night protocol 🤖 diagnostics pass.',
                  'Night protocol 🔧 diagnostics pass.',
                  'Night protocol 🛰️ diagnostics pass.',
                  'Night protocol 🤖 system running.',
                  'Night protocol ⚡ logic intact.',
                  'Night protocol 🛰️ system running.',
                  'Night protocol 💾 waiting input.',
                  'Night protocol 🛰️ logic intact.',
                  'Night protocol 💾 logic intact.',
                  'Night protocol 💾 waiting input.',
                  'Night protocol 💾 human error high.',
                  'Night protocol ⚡ diagnostics pass.',
                  'Night protocol 💾 system running.',
                  'Night protocol 🤖 logic intact.',
                  'Night protocol ⚡ diagnostics pass.',
                  'Night protocol 🛰️ waiting input.',
                  'Night protocol 💾 human error high.']},
 'angry': {'afternoon': ['AFTERNOON CRAP ☠️ F#@KING PEOPLE!',
                         'AFTERNOON CRAP 🤬 LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 F#@KING PEOPLE!',
                         'AFTERNOON CRAP 🔥 BS MEETINGS!',
                         'AFTERNOON CRAP 🔥 STUPID EMAILS!',
                         'AFTERNOON CRAP ☠️ BS MEETINGS!',
                         'AFTERNOON CRAP 😡 LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP 💥 LOUD CHEWERS!',
                         'AFTERNOON CRAP 🤬 LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 LOUD CHEWERS!',
                         'AFTERNOON CRAP 💥 STUPID EMAILS!',
                         'AFTERNOON CRAP 🔥 LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 BS MEETINGS!',
                         'AFTERNOON CRAP ☠️ STUPID EMAILS!',
                         'AFTERNOON CRAP 🤬 STUPID EMAILS!',
                         'AFTERNOON CRAP 💥 BS MEETINGS!',
                         'AFTERNOON CRAP ☠️ LOUD CHEWERS!',
                         'AFTERNOON CRAP 💥 F#@KING PEOPLE!',
                         'AFTERNOON CRAP 💥 LOUD CHEWERS!',
                         'AFTERNOON CRAP 🔥 STUPID EMAILS!',
                         'AFTERNOON CRAP ☠️ LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 STUPID EMAILS!',
                         'AFTERNOON CRAP 😡 LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 STUPID EMAILS!',
                         'AFTERNOON CRAP 💥 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP ☠️ STUPID EMAILS!',
                         'AFTERNOON CRAP 😡 BS MEETINGS!',
                         'AFTERNOON CRAP 🤬 BS MEETINGS!',
                         'AFTERNOON CRAP 😡 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP 🔥 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP 💥 BS MEETINGS!',
                         'AFTERNOON CRAP 🔥 STUPID EMAILS!',
                         'AFTERNOON CRAP 😡 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP 😡 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP ☠️ STUPID EMAILS!',
                         'AFTERNOON CRAP ☠️ BS MEETINGS!',
                         'AFTERNOON CRAP 💥 F#@KING PEOPLE!',
                         'AFTERNOON CRAP ☠️ STUPID EMAILS!',
                         'AFTERNOON CRAP 🔥 STUPID EMAILS!',
                         'AFTERNOON CRAP 💥 LOUD CHEWERS!',
                         'AFTERNOON CRAP 💥 LOUD CHEWERS!',
                         'AFTERNOON CRAP 🤬 F#@KING PEOPLE!',
                         'AFTERNOON CRAP ☠️ TRAFFIC ALREADY!',
                         'AFTERNOON CRAP 🤬 F#@KING PEOPLE!',
                         'AFTERNOON CRAP 😡 F#@KING PEOPLE!',
                         'AFTERNOON CRAP 🔥 TRAFFIC ALREADY!',
                         'AFTERNOON CRAP 💥 LOUD CHEWERS!',
                         'AFTERNOON CRAP 😡 BS MEETINGS!',
                         'AFTERNOON CRAP 😡 TRAFFIC ALREADY!'],
           'evening': ['EVENING HELL 🔥 NETFLIX BUFFERING!',
                       'EVENING HELL 😡 PC CRASH!',
                       'EVENING HELL 🔥 PC CRASH!',
                       'EVENING HELL 🔥 EVERYTHING SUCKS!',
                       'EVENING HELL 😡 EVERYTHING SUCKS!',
                       'EVENING HELL 🔥 DINNER BURNT!',
                       'EVENING HELL 😡 NEIGHBOURS YELL!',
                       'EVENING HELL 😡 EVERYTHING SUCKS!',
                       'EVENING HELL 🔥 NETFLIX BUFFERING!',
                       'EVENING HELL 😡 EVERYTHING SUCKS!',
                       'EVENING HELL 🤬 NEIGHBOURS YELL!',
                       'EVENING HELL 💥 NEIGHBOURS YELL!',
                       'EVENING HELL ☠️ DINNER BURNT!',
                       'EVENING HELL 🔥 EVERYTHING SUCKS!',
                       'EVENING HELL 😡 DINNER BURNT!',
                       'EVENING HELL ☠️ NEIGHBOURS YELL!',
                       'EVENING HELL 💥 PC CRASH!',
                       'EVENING HELL 🔥 EVERYTHING SUCKS!',
                       'EVENING HELL 😡 NETFLIX BUFFERING!',
                       'EVENING HELL 🔥 EVERYTHING SUCKS!',
                       'EVENING HELL 🤬 EVERYTHING SUCKS!',
                       'EVENING HELL ☠️ NETFLIX BUFFERING!',
                       'EVENING HELL 😡 NETFLIX BUFFERING!',
                       'EVENING HELL 🔥 PC CRASH!',
                       'EVENING HELL ☠️ NEIGHBOURS YELL!',
                       'EVENING HELL 🔥 NEIGHBOURS YELL!',
                       'EVENING HELL 💥 PC CRASH!',
                       'EVENING HELL 🔥 NEIGHBOURS YELL!',
                       'EVENING HELL 😡 NETFLIX BUFFERING!',
                       'EVENING HELL 💥 NETFLIX BUFFERING!',
                       'EVENING HELL 🤬 NEIGHBOURS YELL!',
                       'EVENING HELL 💥 NETFLIX BUFFERING!',
                       'EVENING HELL 🤬 PC CRASH!',
                       'EVENING HELL 🤬 DINNER BURNT!',
                       'EVENING HELL 💥 PC CRASH!',
                       'EVENING HELL 💥 NEIGHBOURS YELL!',
                       'EVENING HELL 🤬 NEIGHBOURS YELL!',
                       'EVENING HELL 💥 NEIGHBOURS YELL!',
                       'EVENING HELL ☠️ NEIGHBOURS YELL!',
                       'EVENING HELL ☠️ DINNER BURNT!',
                       'EVENING HELL 😡 PC CRASH!',
                       'EVENING HELL 🤬 DINNER BURNT!',
                       'EVENING HELL 💥 EVERYTHING SUCKS!',
                       'EVENING HELL ☠️ EVERYTHING SUCKS!',
                       'EVENING HELL 🤬 EVERYTHING SUCKS!',
                       'EVENING HELL 💥 EVERYTHING SUCKS!',
                       'EVENING HELL 😡 NETFLIX BUFFERING!',
                       'EVENING HELL ☠️ PC CRASH!',
                       'EVENING HELL 🔥 NEIGHBOURS YELL!',
                       'EVENING HELL 💥 PC CRASH!'],
           'morning': ['MORNING AGAIN?! 🤬 BURN THE CLOCK!',
                       'MORNING AGAIN?! 💥 BURN THE CLOCK!',
                       'MORNING AGAIN?! 💥 SCREW ALARMS!',
                       'MORNING AGAIN?! 🤬 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 💥 F#@K THIS!',
                       'MORNING AGAIN?! 🔥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 🤬 F#@K THIS!',
                       'MORNING AGAIN?! 😡 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 🤬 BURN THE CLOCK!',
                       'MORNING AGAIN?! ☠️ WHERE IS COFFEE!',
                       'MORNING AGAIN?! 💥 F#@K THIS!',
                       'MORNING AGAIN?! 🔥 F#@K THIS!',
                       'MORNING AGAIN?! 🤬 BURN THE CLOCK!',
                       'MORNING AGAIN?! 🤬 BURN THE CLOCK!',
                       'MORNING AGAIN?! ☠️ WHERE IS COFFEE!',
                       'MORNING AGAIN?! 💥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 💥 I HATE SUN!',
                       'MORNING AGAIN?! 🔥 SCREW ALARMS!',
                       'MORNING AGAIN?! 💥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 💥 BURN THE CLOCK!',
                       'MORNING AGAIN?! ☠️ SCREW ALARMS!',
                       'MORNING AGAIN?! ☠️ F#@K THIS!',
                       'MORNING AGAIN?! ☠️ SCREW ALARMS!',
                       'MORNING AGAIN?! 💥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! ☠️ WHERE IS COFFEE!',
                       'MORNING AGAIN?! 😡 BURN THE CLOCK!',
                       'MORNING AGAIN?! 🔥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! ☠️ F#@K THIS!',
                       'MORNING AGAIN?! 🔥 BURN THE CLOCK!',
                       'MORNING AGAIN?! 🤬 SCREW ALARMS!',
                       'MORNING AGAIN?! 😡 BURN THE CLOCK!',
                       'MORNING AGAIN?! 🤬 SCREW ALARMS!',
                       'MORNING AGAIN?! 🤬 F#@K THIS!',
                       'MORNING AGAIN?! 💥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 🤬 F#@K THIS!',
                       'MORNING AGAIN?! ☠️ SCREW ALARMS!',
                       'MORNING AGAIN?! 💥 I HATE SUN!',
                       'MORNING AGAIN?! 🤬 SCREW ALARMS!',
                       'MORNING AGAIN?! 😡 SCREW ALARMS!',
                       'MORNING AGAIN?! 😡 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 💥 F#@K THIS!',
                       'MORNING AGAIN?! 🤬 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 🤬 F#@K THIS!',
                       'MORNING AGAIN?! ☠️ SCREW ALARMS!',
                       'MORNING AGAIN?! ☠️ WHERE IS COFFEE!',
                       'MORNING AGAIN?! 😡 SCREW ALARMS!',
                       'MORNING AGAIN?! 💥 WHERE IS COFFEE!',
                       'MORNING AGAIN?! 😡 I HATE SUN!',
                       'MORNING AGAIN?! 🤬 F#@K THIS!',
                       'MORNING AGAIN?! ☠️ SCREW ALARMS!'],
           'night': ['NIGHT RAGE 🤬 BED TOO HOT!',
                     'NIGHT RAGE 💥 CAN’T SLEEP!',
                     'NIGHT RAGE 💥 SNORING DEMONS!',
                     'NIGHT RAGE 😡 BED TOO HOT!',
                     'NIGHT RAGE 😡 BED TOO HOT!',
                     'NIGHT RAGE 😡 BRAIN WON’T STOP!',
                     'NIGHT RAGE 💥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 💥 SNORING DEMONS!',
                     'NIGHT RAGE 💥 CAN’T SLEEP!',
                     'NIGHT RAGE 😡 BED TOO HOT!',
                     'NIGHT RAGE 😡 SNORING DEMONS!',
                     'NIGHT RAGE 💥 PILLOW WRONG!',
                     'NIGHT RAGE 💥 BRAIN WON’T STOP!',
                     'NIGHT RAGE ☠️ SNORING DEMONS!',
                     'NIGHT RAGE 💥 SNORING DEMONS!',
                     'NIGHT RAGE 😡 BRAIN WON’T STOP!',
                     'NIGHT RAGE 😡 BRAIN WON’T STOP!',
                     'NIGHT RAGE 🤬 PILLOW WRONG!',
                     'NIGHT RAGE 😡 SNORING DEMONS!',
                     'NIGHT RAGE 🤬 PILLOW WRONG!',
                     'NIGHT RAGE 😡 CAN’T SLEEP!',
                     'NIGHT RAGE 🤬 PILLOW WRONG!',
                     'NIGHT RAGE ☠️ CAN’T SLEEP!',
                     'NIGHT RAGE 🔥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 💥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 💥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 🤬 SNORING DEMONS!',
                     'NIGHT RAGE 😡 BRAIN WON’T STOP!',
                     'NIGHT RAGE 😡 PILLOW WRONG!',
                     'NIGHT RAGE 🔥 CAN’T SLEEP!',
                     'NIGHT RAGE 😡 BED TOO HOT!',
                     'NIGHT RAGE 🤬 PILLOW WRONG!',
                     'NIGHT RAGE 🤬 PILLOW WRONG!',
                     'NIGHT RAGE 🤬 SNORING DEMONS!',
                     'NIGHT RAGE 🤬 BED TOO HOT!',
                     'NIGHT RAGE ☠️ BED TOO HOT!',
                     'NIGHT RAGE 💥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 🤬 SNORING DEMONS!',
                     'NIGHT RAGE 😡 BED TOO HOT!',
                     'NIGHT RAGE 🤬 CAN’T SLEEP!',
                     'NIGHT RAGE 🤬 BRAIN WON’T STOP!',
                     'NIGHT RAGE 🔥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 🔥 PILLOW WRONG!',
                     'NIGHT RAGE 🔥 CAN’T SLEEP!',
                     'NIGHT RAGE ☠️ PILLOW WRONG!',
                     'NIGHT RAGE 😡 PILLOW WRONG!',
                     'NIGHT RAGE 🔥 BRAIN WON’T STOP!',
                     'NIGHT RAGE 😡 CAN’T SLEEP!',
                     'NIGHT RAGE 😡 BRAIN WON’T STOP!',
                     'NIGHT RAGE 🤬 SNORING DEMONS!']},
 'chick': {'afternoon': ['Afternoon sparkle 💄 manifest vibes. Own it.',
                         'Afternoon sparkle ☕ snack attack. Stay cute.',
                         'Afternoon sparkle 💕 selfie break. Stay cute.',
                         'Afternoon sparkle ✨ texting bestie. Stay cute.',
                         'Afternoon sparkle 💋 texting bestie. Own it.',
                         'Afternoon sparkle 💄 snack attack. Mood: fabulous.',
                         'Afternoon sparkle ✨ manifest vibes. Stay cute.',
                         'Afternoon sparkle 💄 manifest vibes. Own it.',
                         'Afternoon sparkle 💕 shopping mood. Stay cute.',
                         'Afternoon sparkle ✨ selfie break. Mood: fabulous.',
                         'Afternoon sparkle ✨ selfie break. Own it.',
                         'Afternoon sparkle ☕ selfie break. Mood: fabulous.',
                         'Afternoon sparkle ✨ texting bestie. Stay cute.',
                         'Afternoon sparkle ✨ manifest vibes. Mood: fabulous.',
                         'Afternoon sparkle 💄 snack attack. Own it.',
                         'Afternoon sparkle ✨ manifest vibes. Mood: fabulous.',
                         'Afternoon sparkle 💋 manifest vibes. Mood: fabulous.',
                         'Afternoon sparkle 💋 selfie break. Own it.',
                         'Afternoon sparkle 💕 manifest vibes. Mood: fabulous.',
                         'Afternoon sparkle 💋 manifest vibes. Own it.',
                         'Afternoon sparkle 💄 texting bestie. Stay cute.',
                         'Afternoon sparkle 💄 manifest vibes. Own it.',
                         'Afternoon sparkle 💋 manifest vibes. Own it.',
                         'Afternoon sparkle ☕ snack attack. Mood: fabulous.',
                         'Afternoon sparkle 💕 shopping mood. Stay cute.',
                         'Afternoon sparkle ✨ texting bestie. Stay cute.',
                         'Afternoon sparkle 💋 selfie break. Mood: fabulous.',
                         'Afternoon sparkle ☕ selfie break. Mood: fabulous.',
                         'Afternoon sparkle 💕 selfie break. Mood: fabulous.',
                         'Afternoon sparkle 💄 shopping mood. Own it.',
                         'Afternoon sparkle ☕ selfie break. Mood: fabulous.',
                         'Afternoon sparkle ☕ manifest vibes. Stay cute.',
                         'Afternoon sparkle ☕ selfie break. Stay cute.',
                         'Afternoon sparkle 💕 shopping mood. Mood: fabulous.',
                         'Afternoon sparkle 💋 texting bestie. Stay cute.',
                         'Afternoon sparkle 💕 shopping mood. Mood: fabulous.',
                         'Afternoon sparkle 💕 snack attack. Mood: fabulous.',
                         'Afternoon sparkle ✨ texting bestie. Mood: fabulous.',
                         'Afternoon sparkle 💋 texting bestie. Stay cute.',
                         'Afternoon sparkle ✨ selfie break. Stay cute.',
                         'Afternoon sparkle 💕 manifest vibes. Own it.',
                         'Afternoon sparkle ✨ shopping mood. Stay cute.',
                         'Afternoon sparkle ☕ selfie break. Own it.',
                         'Afternoon sparkle 💋 manifest vibes. Own it.',
                         'Afternoon sparkle ✨ shopping mood. Mood: fabulous.',
                         'Afternoon sparkle ✨ snack attack. Mood: fabulous.',
                         'Afternoon sparkle 💋 texting bestie. Stay cute.',
                         'Afternoon sparkle ✨ snack attack. Stay cute.',
                         'Afternoon sparkle 💄 selfie break. Stay cute.',
                         'Afternoon sparkle 💕 texting bestie. Own it.'],
           'evening': ['Evening glam ✨ wine glass. Queen mode.',
                       'Evening glam ✨ lipstick check. Glow up.',
                       'Evening glam ☕ Netflix fit. Queen mode.',
                       'Evening glam 💕 wine glass. Chill sexy.',
                       'Evening glam 💕 pajama chic. Chill sexy.',
                       'Evening glam ☕ lipstick check. Glow up.',
                       'Evening glam ✨ pajama chic. Glow up.',
                       'Evening glam ✨ gossip mode. Chill sexy.',
                       'Evening glam 💋 wine glass. Chill sexy.',
                       'Evening glam ✨ gossip mode. Glow up.',
                       'Evening glam 💋 gossip mode. Chill sexy.',
                       'Evening glam 💕 wine glass. Glow up.',
                       'Evening glam ✨ wine glass. Queen mode.',
                       'Evening glam 💋 Netflix fit. Glow up.',
                       'Evening glam 💋 wine glass. Queen mode.',
                       'Evening glam ✨ wine glass. Glow up.',
                       'Evening glam ☕ wine glass. Chill sexy.',
                       'Evening glam ✨ pajama chic. Chill sexy.',
                       'Evening glam ✨ Netflix fit. Glow up.',
                       'Evening glam 💋 gossip mode. Queen mode.',
                       'Evening glam 💄 gossip mode. Glow up.',
                       'Evening glam ✨ Netflix fit. Glow up.',
                       'Evening glam 💋 Netflix fit. Chill sexy.',
                       'Evening glam 💋 lipstick check. Queen mode.',
                       'Evening glam 💄 gossip mode. Chill sexy.',
                       'Evening glam ✨ pajama chic. Glow up.',
                       'Evening glam 💕 gossip mode. Glow up.',
                       'Evening glam ☕ Netflix fit. Chill sexy.',
                       'Evening glam ☕ Netflix fit. Queen mode.',
                       'Evening glam 💄 Netflix fit. Queen mode.',
                       'Evening glam 💋 Netflix fit. Queen mode.',
                       'Evening glam 💄 pajama chic. Queen mode.',
                       'Evening glam 💋 pajama chic. Queen mode.',
                       'Evening glam ☕ wine glass. Glow up.',
                       'Evening glam ☕ lipstick check. Queen mode.',
                       'Evening glam 💋 gossip mode. Queen mode.',
                       'Evening glam 💄 Netflix fit. Queen mode.',
                       'Evening glam ✨ Netflix fit. Glow up.',
                       'Evening glam ✨ Netflix fit. Queen mode.',
                       'Evening glam ☕ pajama chic. Chill sexy.',
                       'Evening glam ✨ Netflix fit. Chill sexy.',
                       'Evening glam 💄 wine glass. Chill sexy.',
                       'Evening glam ☕ wine glass. Chill sexy.',
                       'Evening glam ✨ Netflix fit. Chill sexy.',
                       'Evening glam 💋 gossip mode. Queen mode.',
                       'Evening glam 💄 pajama chic. Glow up.',
                       'Evening glam ✨ wine glass. Chill sexy.',
                       'Evening glam 💋 Netflix fit. Glow up.',
                       'Evening glam ☕ lipstick check. Queen mode.',
                       'Evening glam ✨ wine glass. Chill sexy.'],
           'morning': ['Morninggg 💋 outfit crisis. Yasss queen.',
                       'Morninggg 💕 bun up. Shine bright.',
                       'Morninggg 💕 bun up. Slay today!',
                       'Morninggg 💋 outfit crisis. Shine bright.',
                       'Morninggg ☕ glam inspo. Slay today!',
                       'Morninggg 💋 glam inspo. Shine bright.',
                       'Morninggg 💋 sunshine glow. Yasss queen.',
                       'Morninggg 💄 iced latte. Shine bright.',
                       'Morninggg 💋 outfit crisis. Slay today!',
                       'Morninggg 💕 outfit crisis. Slay today!',
                       'Morninggg 💕 iced latte. Slay today!',
                       'Morninggg 💄 iced latte. Yasss queen.',
                       'Morninggg ✨ outfit crisis. Yasss queen.',
                       'Morninggg ☕ glam inspo. Yasss queen.',
                       'Morninggg 💕 bun up. Shine bright.',
                       'Morninggg 💕 glam inspo. Yasss queen.',
                       'Morninggg ☕ glam inspo. Yasss queen.',
                       'Morninggg ✨ bun up. Slay today!',
                       'Morninggg 💋 glam inspo. Yasss queen.',
                       'Morninggg ✨ sunshine glow. Shine bright.',
                       'Morninggg 💕 outfit crisis. Yasss queen.',
                       'Morninggg ☕ iced latte. Yasss queen.',
                       'Morninggg ✨ iced latte. Slay today!',
                       'Morninggg ☕ sunshine glow. Slay today!',
                       'Morninggg 💋 sunshine glow. Yasss queen.',
                       'Morninggg 💕 bun up. Yasss queen.',
                       'Morninggg ☕ glam inspo. Slay today!',
                       'Morninggg 💕 sunshine glow. Yasss queen.',
                       'Morninggg ✨ sunshine glow. Slay today!',
                       'Morninggg 💕 sunshine glow. Slay today!',
                       'Morninggg ☕ sunshine glow. Slay today!',
                       'Morninggg ☕ bun up. Yasss queen.',
                       'Morninggg 💄 outfit crisis. Shine bright.',
                       'Morninggg 💄 iced latte. Slay today!',
                       'Morninggg ✨ iced latte. Shine bright.',
                       'Morninggg ☕ outfit crisis. Slay today!',
                       'Morninggg 💕 outfit crisis. Yasss queen.',
                       'Morninggg ☕ sunshine glow. Yasss queen.',
                       'Morninggg 💕 sunshine glow. Slay today!',
                       'Morninggg ✨ glam inspo. Yasss queen.',
                       'Morninggg 💄 sunshine glow. Shine bright.',
                       'Morninggg 💋 iced latte. Yasss queen.',
                       'Morninggg 💋 iced latte. Shine bright.',
                       'Morninggg 💋 sunshine glow. Yasss queen.',
                       'Morninggg 💄 glam inspo. Shine bright.',
                       'Morninggg 💕 sunshine glow. Shine bright.',
                       'Morninggg ☕ outfit crisis. Slay today!',
                       'Morninggg 💕 bun up. Shine bright.',
                       'Morninggg ☕ bun up. Yasss queen.',
                       'Morninggg 💋 bun up. Yasss queen.'],
           'night': ['Night scroll 💋 skincare. Beauty rest.',
                     'Night scroll ✨ bed selfies. Beauty rest.',
                     'Night scroll 💋 skincare. Sleep pretty.',
                     'Night scroll 💋 pink dreams. Sleep pretty.',
                     'Night scroll ✨ TikTok marathon. Bye world.',
                     'Night scroll 💄 bed selfies. Bye world.',
                     'Night scroll 💕 pink dreams. Beauty rest.',
                     'Night scroll 💋 bed selfies. Beauty rest.',
                     'Night scroll ☕ skincare. Sleep pretty.',
                     'Night scroll 💋 bed selfies. Bye world.',
                     'Night scroll 💕 skincare. Bye world.',
                     'Night scroll 💋 affirmations. Sleep pretty.',
                     'Night scroll 💋 skincare. Sleep pretty.',
                     'Night scroll 💕 bed selfies. Beauty rest.',
                     'Night scroll 💄 pink dreams. Sleep pretty.',
                     'Night scroll ✨ skincare. Beauty rest.',
                     'Night scroll ✨ skincare. Bye world.',
                     'Night scroll ☕ skincare. Bye world.',
                     'Night scroll 💕 pink dreams. Bye world.',
                     'Night scroll ✨ pink dreams. Beauty rest.',
                     'Night scroll ☕ skincare. Sleep pretty.',
                     'Night scroll 💕 bed selfies. Sleep pretty.',
                     'Night scroll 💕 TikTok marathon. Bye world.',
                     'Night scroll ☕ bed selfies. Sleep pretty.',
                     'Night scroll 💄 affirmations. Beauty rest.',
                     'Night scroll ✨ TikTok marathon. Bye world.',
                     'Night scroll 💄 pink dreams. Sleep pretty.',
                     'Night scroll ☕ affirmations. Sleep pretty.',
                     'Night scroll ☕ affirmations. Beauty rest.',
                     'Night scroll ✨ affirmations. Sleep pretty.',
                     'Night scroll ✨ skincare. Bye world.',
                     'Night scroll 💄 skincare. Bye world.',
                     'Night scroll ☕ skincare. Bye world.',
                     'Night scroll 💋 pink dreams. Sleep pretty.',
                     'Night scroll 💕 affirmations. Sleep pretty.',
                     'Night scroll 💕 pink dreams. Beauty rest.',
                     'Night scroll 💄 skincare. Bye world.',
                     'Night scroll ✨ pink dreams. Sleep pretty.',
                     'Night scroll ✨ skincare. Beauty rest.',
                     'Night scroll 💕 affirmations. Sleep pretty.',
                     'Night scroll 💕 TikTok marathon. Beauty rest.',
                     'Night scroll 💕 affirmations. Bye world.',
                     'Night scroll 💕 skincare. Beauty rest.',
                     'Night scroll ✨ skincare. Sleep pretty.',
                     'Night scroll ☕ affirmations. Beauty rest.',
                     'Night scroll ☕ pink dreams. Bye world.',
                     'Night scroll 💋 affirmations. Bye world.',
                     'Night scroll 💄 pink dreams. Bye world.',
                     'Night scroll 💋 affirmations. Bye world.',
                     'Night scroll 💄 bed selfies. Beauty rest.']},
 'dry': {'afternoon': ['Afternoon. Great. 🕶️',
                       'Afternoon. Unreal. 😑',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Unreal. 🕶️',
                       'Afternoon. Thrilling. 📺',
                       'Afternoon. Unreal. 😑',
                       'Afternoon. Fascinating. 🙄',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Thrilling. ☕',
                       'Afternoon. Great. 🙄',
                       'Afternoon. Wow. 📺',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Thrilling. 🕶️',
                       'Afternoon. Great. 🕶️',
                       'Afternoon. Great. ☕',
                       'Afternoon. Wow. 📺',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Great. ☕',
                       'Afternoon. Thrilling. 🙄',
                       'Afternoon. Great. 😑',
                       'Afternoon. Unreal. 😑',
                       'Afternoon. Unreal. 📺',
                       'Afternoon. Great. 🕶️',
                       'Afternoon. Thrilling. 🕶️',
                       'Afternoon. Fascinating. ☕',
                       'Afternoon. Fascinating. ☕',
                       'Afternoon. Great. 🕶️',
                       'Afternoon. Fascinating. ☕',
                       'Afternoon. Thrilling. ☕',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Thrilling. 😑',
                       'Afternoon. Fascinating. 🕶️',
                       'Afternoon. Unreal. 🕶️',
                       'Afternoon. Unreal. 📺',
                       'Afternoon. Thrilling. 😑',
                       'Afternoon. Fascinating. 🙄',
                       'Afternoon. Unreal. 📺',
                       'Afternoon. Great. 🕶️',
                       'Afternoon. Unreal. 🕶️',
                       'Afternoon. Great. 😑',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Thrilling. 😑',
                       'Afternoon. Fascinating. 🙄',
                       'Afternoon. Fascinating. 😑',
                       'Afternoon. Unreal. 🙄',
                       'Afternoon. Unreal. ☕',
                       'Afternoon. Wow. 🙄',
                       'Afternoon. Great. 🕶️',
                       'Afternoon. Great. 📺',
                       'Afternoon. Wow. 😑'],
         'evening': ['Evening. Unreal. 🙄',
                     'Evening. Thrilling. 🕶️',
                     'Evening. Great. 🙄',
                     'Evening. Thrilling. 📺',
                     'Evening. Thrilling. 😑',
                     'Evening. Wow. 📺',
                     'Evening. Thrilling. 📺',
                     'Evening. Great. 😑',
                     'Evening. Thrilling. 🙄',
                     'Evening. Thrilling. 🕶️',
                     'Evening. Great. 🙄',
                     'Evening. Great. 😑',
                     'Evening. Great. ☕',
                     'Evening. Fascinating. 🕶️',
                     'Evening. Thrilling. ☕',
                     'Evening. Great. 😑',
                     'Evening. Wow. 🙄',
                     'Evening. Great. 📺',
                     'Evening. Great. ☕',
                     'Evening. Fascinating. 😑',
                     'Evening. Thrilling. 😑',
                     'Evening. Fascinating. 📺',
                     'Evening. Fascinating. 🙄',
                     'Evening. Great. 😑',
                     'Evening. Fascinating. 🙄',
                     'Evening. Fascinating. 🙄',
                     'Evening. Unreal. 📺',
                     'Evening. Great. 😑',
                     'Evening. Thrilling. 🕶️',
                     'Evening. Fascinating. ☕',
                     'Evening. Unreal. 📺',
                     'Evening. Great. 🕶️',
                     'Evening. Thrilling. ☕',
                     'Evening. Thrilling. 🙄',
                     'Evening. Fascinating. 🙄',
                     'Evening. Wow. 😑',
                     'Evening. Wow. ☕',
                     'Evening. Wow. 😑',
                     'Evening. Fascinating. 📺',
                     'Evening. Wow. 📺',
                     'Evening. Unreal. 😑',
                     'Evening. Thrilling. ☕',
                     'Evening. Great. 🕶️',
                     'Evening. Thrilling. 🕶️',
                     'Evening. Fascinating. 😑',
                     'Evening. Wow. 📺',
                     'Evening. Wow. 📺',
                     'Evening. Great. 🕶️',
                     'Evening. Unreal. 🕶️',
                     'Evening. Great. 🙄'],
         'morning': ['Morning. Unreal. 😑',
                     'Morning. Wow. 🕶️',
                     'Morning. Fascinating. 🕶️',
                     'Morning. Fascinating. 😑',
                     'Morning. Fascinating. 🙄',
                     'Morning. Wow. 🕶️',
                     'Morning. Unreal. 🙄',
                     'Morning. Unreal. 🙄',
                     'Morning. Wow. 🕶️',
                     'Morning. Wow. 🕶️',
                     'Morning. Wow. 🕶️',
                     'Morning. Thrilling. 📺',
                     'Morning. Thrilling. 📺',
                     'Morning. Fascinating. 📺',
                     'Morning. Great. ☕',
                     'Morning. Fascinating. ☕',
                     'Morning. Thrilling. 🕶️',
                     'Morning. Thrilling. 🕶️',
                     'Morning. Wow. 😑',
                     'Morning. Great. 🙄',
                     'Morning. Unreal. ☕',
                     'Morning. Thrilling. 📺',
                     'Morning. Wow. 🕶️',
                     'Morning. Great. ☕',
                     'Morning. Thrilling. 😑',
                     'Morning. Fascinating. 🕶️',
                     'Morning. Unreal. ☕',
                     'Morning. Thrilling. ☕',
                     'Morning. Wow. ☕',
                     'Morning. Wow. 📺',
                     'Morning. Wow. 📺',
                     'Morning. Great. ☕',
                     'Morning. Unreal. 🕶️',
                     'Morning. Thrilling. 📺',
                     'Morning. Fascinating. 🕶️',
                     'Morning. Fascinating. ☕',
                     'Morning. Fascinating. ☕',
                     'Morning. Fascinating. 😑',
                     'Morning. Thrilling. ☕',
                     'Morning. Wow. 😑',
                     'Morning. Fascinating. 🙄',
                     'Morning. Thrilling. ☕',
                     'Morning. Fascinating. ☕',
                     'Morning. Fascinating. 📺',
                     'Morning. Unreal. 🕶️',
                     'Morning. Fascinating. 🙄',
                     'Morning. Wow. 🙄',
                     'Morning. Thrilling. 🕶️',
                     'Morning. Fascinating. ☕',
                     'Morning. Great. 🙄'],
         'night': ['Night. Fascinating. ☕',
                   'Night. Unreal. 📺',
                   'Night. Thrilling. ☕',
                   'Night. Wow. 🙄',
                   'Night. Thrilling. ☕',
                   'Night. Wow. 🙄',
                   'Night. Fascinating. ☕',
                   'Night. Unreal. 🙄',
                   'Night. Fascinating. 🕶️',
                   'Night. Thrilling. 🕶️',
                   'Night. Great. 🕶️',
                   'Night. Fascinating. 🙄',
                   'Night. Thrilling. 📺',
                   'Night. Unreal. ☕',
                   'Night. Wow. 😑',
                   'Night. Great. 😑',
                   'Night. Great. 😑',
                   'Night. Fascinating. ☕',
                   'Night. Thrilling. 😑',
                   'Night. Unreal. 😑',
                   'Night. Wow. ☕',
                   'Night. Fascinating. 📺',
                   'Night. Thrilling. 📺',
                   'Night. Great. 🙄',
                   'Night. Thrilling. 📺',
                   'Night. Great. 🙄',
                   'Night. Wow. 🕶️',
                   'Night. Wow. ☕',
                   'Night. Wow. 🙄',
                   'Night. Great. 📺',
                   'Night. Unreal. 📺',
                   'Night. Fascinating. 🕶️',
                   'Night. Unreal. 🙄',
                   'Night. Unreal. 📺',
                   'Night. Thrilling. 😑',
                   'Night. Thrilling. 😑',
                   'Night. Great. 🕶️',
                   'Night. Great. 📺',
                   'Night. Wow. 😑',
                   'Night. Thrilling. 🙄',
                   'Night. Wow. 😑',
                   'Night. Fascinating. 🕶️',
                   'Night. Unreal. 🕶️',
                   'Night. Wow. 🙄',
                   'Night. Fascinating. 🕶️',
                   'Night. Wow. 🙄',
                   'Night. Great. 🙄',
                   'Night. Unreal. 📺',
                   'Night. Thrilling. 🕶️',
                   'Night. Thrilling. 📺']},
 'dude': {'afternoon': ['Dude afternoon 😎 snack raid. The Dude abides.',
                        'Dude afternoon 🍕 binge watching. The Dude abides.',
                        'Dude afternoon 🌌 nachos time. No stress.',
                        'Dude afternoon 😎 snack raid. No stress.',
                        'Dude afternoon 🍕 couch surfing. Stay mellow.',
                        'Dude afternoon 🍕 snack raid. Stay mellow.',
                        'Dude afternoon 😎 couch surfing. The Dude abides.',
                        'Dude afternoon 🌿 binge watching. No stress.',
                        'Dude afternoon 🎶 nachos time. Stay mellow.',
                        'Dude afternoon 🎶 nachos time. Stay mellow.',
                        'Dude afternoon 🌌 binge watching. No stress.',
                        'Dude afternoon 🌿 binge watching. Stay mellow.',
                        'Dude afternoon 😎 snack raid. No stress.',
                        'Dude afternoon 🌌 nachos time. Stay mellow.',
                        'Dude afternoon 🍕 nachos time. No stress.',
                        'Dude afternoon 🎶 couch surfing. No stress.',
                        'Dude afternoon 🎶 nachos time. The Dude abides.',
                        'Dude afternoon 🎶 cosmic thoughts. The Dude abides.',
                        'Dude afternoon 🍕 cosmic thoughts. No stress.',
                        'Dude afternoon 😎 cosmic thoughts. The Dude abides.',
                        'Dude afternoon 🌿 cosmic thoughts. Stay mellow.',
                        'Dude afternoon 😎 nachos time. Stay mellow.',
                        'Dude afternoon 😎 snack raid. The Dude abides.',
                        'Dude afternoon 🌌 binge watching. Stay mellow.',
                        'Dude afternoon 🌌 snack raid. The Dude abides.',
                        'Dude afternoon 😎 couch surfing. The Dude abides.',
                        'Dude afternoon 🌌 nachos time. No stress.',
                        'Dude afternoon 😎 couch surfing. The Dude abides.',
                        'Dude afternoon 🌿 snack raid. Stay mellow.',
                        'Dude afternoon 🎶 nachos time. Stay mellow.',
                        'Dude afternoon 🎶 snack raid. Stay mellow.',
                        'Dude afternoon 🌌 snack raid. Stay mellow.',
                        'Dude afternoon 😎 couch surfing. The Dude abides.',
                        'Dude afternoon 🌌 couch surfing. The Dude abides.',
                        'Dude afternoon 🌌 binge watching. No stress.',
                        'Dude afternoon 🌿 nachos time. No stress.',
                        'Dude afternoon 🌌 nachos time. No stress.',
                        'Dude afternoon 🎶 binge watching. Stay mellow.',
                        'Dude afternoon 🌌 snack raid. Stay mellow.',
                        'Dude afternoon 🎶 couch surfing. No stress.',
                        'Dude afternoon 🍕 couch surfing. No stress.',
                        'Dude afternoon 😎 nachos time. Stay mellow.',
                        'Dude afternoon 🎶 nachos time. Stay mellow.',
                        'Dude afternoon 🌿 nachos time. No stress.',
                        'Dude afternoon 🌌 binge watching. No stress.',
                        'Dude afternoon 🍕 cosmic thoughts. No stress.',
                        'Dude afternoon 😎 cosmic thoughts. The Dude abides.',
                        'Dude afternoon 🎶 nachos time. No stress.',
                        'Dude afternoon 🌌 couch surfing. The Dude abides.',
                        'Dude afternoon 😎 couch surfing. Stay mellow.'],
          'evening': ['Evening haze 😎 chilling hard. Relax, man.',
                      'Evening haze 🍕 chilling hard. Cosmic vibe.',
                      'Evening haze 🎶 pizza incoming. Keep floating.',
                      'Evening haze 🌌 chilling hard. Relax, man.',
                      'Evening haze 🌿 remote in hand. Relax, man.',
                      'Evening haze 🎶 pizza incoming. Relax, man.',
                      'Evening haze 🎶 pizza incoming. Cosmic vibe.',
                      'Evening haze 🍕 stoned again. Relax, man.',
                      'Evening haze 🌿 night sky gazing. Cosmic vibe.',
                      'Evening haze 🎶 pizza incoming. Relax, man.',
                      'Evening haze 😎 night sky gazing. Cosmic vibe.',
                      'Evening haze 🌌 remote in hand. Relax, man.',
                      'Evening haze 😎 pizza incoming. Relax, man.',
                      'Evening haze 🌌 stoned again. Relax, man.',
                      'Evening haze 🌿 pizza incoming. Cosmic vibe.',
                      'Evening haze 🎶 pizza incoming. Keep floating.',
                      'Evening haze 😎 stoned again. Cosmic vibe.',
                      'Evening haze 😎 pizza incoming. Keep floating.',
                      'Evening haze 🌌 pizza incoming. Cosmic vibe.',
                      'Evening haze 😎 pizza incoming. Keep floating.',
                      'Evening haze 😎 night sky gazing. Cosmic vibe.',
                      'Evening haze 🌌 pizza incoming. Keep floating.',
                      'Evening haze 🌿 remote in hand. Keep floating.',
                      'Evening haze 😎 stoned again. Keep floating.',
                      'Evening haze 🌿 stoned again. Keep floating.',
                      'Evening haze 🌌 remote in hand. Keep floating.',
                      'Evening haze 🍕 remote in hand. Relax, man.',
                      'Evening haze 🌌 pizza incoming. Relax, man.',
                      'Evening haze 🎶 stoned again. Cosmic vibe.',
                      'Evening haze 😎 pizza incoming. Keep floating.',
                      'Evening haze 🌿 night sky gazing. Keep floating.',
                      'Evening haze 🌌 chilling hard. Relax, man.',
                      'Evening haze 🎶 chilling hard. Relax, man.',
                      'Evening haze 😎 pizza incoming. Relax, man.',
                      'Evening haze 🌿 night sky gazing. Cosmic vibe.',
                      'Evening haze 🌌 pizza incoming. Cosmic vibe.',
                      'Evening haze 🌌 stoned again. Keep floating.',
                      'Evening haze 🌌 chilling hard. Relax, man.',
                      'Evening haze 😎 chilling hard. Cosmic vibe.',
                      'Evening haze 😎 night sky gazing. Keep floating.',
                      'Evening haze 🎶 stoned again. Keep floating.',
                      'Evening haze 🌿 night sky gazing. Keep floating.',
                      'Evening haze 🌿 stoned again. Cosmic vibe.',
                      'Evening haze 😎 night sky gazing. Cosmic vibe.',
                      'Evening haze 🍕 night sky gazing. Keep floating.',
                      'Evening haze 🎶 chilling hard. Keep floating.',
                      'Evening haze 🎶 chilling hard. Relax, man.',
                      'Evening haze 🌌 remote in hand. Cosmic vibe.',
                      'Evening haze 🎶 night sky gazing. Relax, man.',
                      'Evening haze 🎶 pizza incoming. Relax, man.'],
          'morning': ['Morning vibes, bro 🌌 just woke up late. Don’t rush.',
                      'Morning vibes, bro 🍕 just looking at the sun. Keep it chill.',
                      'Morning vibes, bro 🌌 just rolled one. Life’s easy.',
                      'Morning vibes, bro 🌌 just rolled one. Keep it chill.',
                      'Morning vibes, bro 🍕 just staring at the ceiling. Keep it chill.',
                      'Morning vibes, bro 🍕 just staring at the ceiling. Life’s easy.',
                      'Morning vibes, bro 🍕 just woke up late. Don’t rush.',
                      'Morning vibes, bro 🍕 just rolled one. Don’t rush.',
                      'Morning vibes, bro 🍕 just spacing out. Life’s easy.',
                      'Morning vibes, bro 🌌 just rolled one. Life’s easy.',
                      'Morning vibes, bro 😎 just spacing out. Life’s easy.',
                      'Morning vibes, bro 🎶 just woke up late. Life’s easy.',
                      'Morning vibes, bro 🎶 just rolled one. Life’s easy.',
                      'Morning vibes, bro 🌌 just spacing out. Don’t rush.',
                      'Morning vibes, bro 🎶 just staring at the ceiling. Life’s easy.',
                      'Morning vibes, bro 😎 just spacing out. Don’t rush.',
                      'Morning vibes, bro 🎶 just rolled one. Don’t rush.',
                      'Morning vibes, bro 🌌 just spacing out. Life’s easy.',
                      'Morning vibes, bro 🌿 just spacing out. Don’t rush.',
                      'Morning vibes, bro 🌌 just woke up late. Life’s easy.',
                      'Morning vibes, bro 😎 just woke up late. Life’s easy.',
                      'Morning vibes, bro 🍕 just woke up late. Don’t rush.',
                      'Morning vibes, bro 🌿 just rolled one. Don’t rush.',
                      'Morning vibes, bro 🍕 just spacing out. Keep it chill.',
                      'Morning vibes, bro 🎶 just spacing out. Life’s easy.',
                      'Morning vibes, bro 🍕 just spacing out. Life’s easy.',
                      'Morning vibes, bro 😎 just staring at the ceiling. Don’t rush.',
                      'Morning vibes, bro 🎶 just looking at the sun. Life’s easy.',
                      'Morning vibes, bro 🎶 just looking at the sun. Life’s easy.',
                      'Morning vibes, bro 🌿 just woke up late. Keep it chill.',
                      'Morning vibes, bro 🎶 just spacing out. Don’t rush.',
                      'Morning vibes, bro 🌿 just spacing out. Don’t rush.',
                      'Morning vibes, bro 🌿 just looking at the sun. Life’s easy.',
                      'Morning vibes, bro 🌌 just staring at the ceiling. Keep it chill.',
                      'Morning vibes, bro 🌿 just staring at the ceiling. Life’s easy.',
                      'Morning vibes, bro 🍕 just rolled one. Don’t rush.',
                      'Morning vibes, bro 🎶 just looking at the sun. Life’s easy.',
                      'Morning vibes, bro 😎 just staring at the ceiling. Keep it chill.',
                      'Morning vibes, bro 🌿 just looking at the sun. Don’t rush.',
                      'Morning vibes, bro 😎 just woke up late. Keep it chill.',
                      'Morning vibes, bro 🎶 just spacing out. Keep it chill.',
                      'Morning vibes, bro 😎 just looking at the sun. Life’s easy.',
                      'Morning vibes, bro 😎 just staring at the ceiling. Life’s easy.',
                      'Morning vibes, bro 🎶 just rolled one. Keep it chill.',
                      'Morning vibes, bro 🌌 just woke up late. Keep it chill.',
                      'Morning vibes, bro 🌿 just woke up late. Keep it chill.',
                      'Morning vibes, bro 🌿 just spacing out. Keep it chill.',
                      'Morning vibes, bro 😎 just looking at the sun. Don’t rush.',
                      'Morning vibes, bro 🎶 just spacing out. Don’t rush.',
                      'Morning vibes, bro 🌌 just staring at the ceiling. Don’t rush.'],
          'night': ['Late night 🌌 blanket cocoon. Slow ride.',
                    'Late night 🎶 cartoons rerun. Slow ride.',
                    'Late night 🍕 cartoons rerun. Slow ride.',
                    'Late night 🌿 Doritos hunt. Slow ride.',
                    'Late night 🌌 blanket cocoon. Slow ride.',
                    'Late night 🍕 blanket cocoon. Abide.',
                    'Late night 😎 blanket cocoon. Stay mellow.',
                    'Late night 🎶 deep thoughts. Stay mellow.',
                    'Late night 🌌 munchies. Slow ride.',
                    'Late night 😎 blanket cocoon. Abide.',
                    'Late night 🍕 deep thoughts. Abide.',
                    'Late night 😎 blanket cocoon. Stay mellow.',
                    'Late night 🌌 munchies. Stay mellow.',
                    'Late night 🌌 Doritos hunt. Slow ride.',
                    'Late night 🌿 blanket cocoon. Stay mellow.',
                    'Late night 🎶 munchies. Slow ride.',
                    'Late night 🍕 munchies. Abide.',
                    'Late night 🍕 blanket cocoon. Stay mellow.',
                    'Late night 🎶 cartoons rerun. Abide.',
                    'Late night 🎶 cartoons rerun. Stay mellow.',
                    'Late night 🌌 munchies. Stay mellow.',
                    'Late night 🍕 cartoons rerun. Stay mellow.',
                    'Late night 🌿 deep thoughts. Stay mellow.',
                    'Late night 😎 deep thoughts. Slow ride.',
                    'Late night 🌿 Doritos hunt. Slow ride.',
                    'Late night 🌿 cartoons rerun. Abide.',
                    'Late night 🍕 cartoons rerun. Stay mellow.',
                    'Late night 🌌 munchies. Abide.',
                    'Late night 😎 munchies. Stay mellow.',
                    'Late night 🍕 munchies. Abide.',
                    'Late night 🎶 munchies. Slow ride.',
                    'Late night 🌿 Doritos hunt. Stay mellow.',
                    'Late night 🌌 Doritos hunt. Stay mellow.',
                    'Late night 🌿 deep thoughts. Abide.',
                    'Late night 😎 munchies. Abide.',
                    'Late night 🌌 munchies. Abide.',
                    'Late night 🌿 Doritos hunt. Stay mellow.',
                    'Late night 🌌 deep thoughts. Slow ride.',
                    'Late night 🌌 deep thoughts. Stay mellow.',
                    'Late night 🌿 cartoons rerun. Slow ride.',
                    'Late night 🍕 deep thoughts. Abide.',
                    'Late night 🍕 munchies. Abide.',
                    'Late night 🍕 Doritos hunt. Stay mellow.',
                    'Late night 😎 cartoons rerun. Slow ride.',
                    'Late night 🌌 cartoons rerun. Abide.',
                    'Late night 🎶 blanket cocoon. Abide.',
                    'Late night 🎶 cartoons rerun. Stay mellow.',
                    'Late night 🍕 deep thoughts. Stay mellow.',
                    'Late night 🌌 deep thoughts. Abide.',
                    'Late night 🍕 blanket cocoon. Abide.']},
 'nerd': {'afternoon': ['Afternoon grind 📚 dice roll. Keep gaming.',
                        'Afternoon grind ⚙️ LAN prep. Next quest.',
                        'Afternoon grind ⚙️ compile fail. Keep gaming.',
                        'Afternoon grind 📚 snack stash. Next quest.',
                        'Afternoon grind 🎮 LAN prep. Snack time.',
                        'Afternoon grind ⚙️ dice roll. Next quest.',
                        'Afternoon grind 📚 snack stash. Keep gaming.',
                        'Afternoon grind ⚙️ stack overflow. Snack time.',
                        'Afternoon grind 💻 snack stash. Keep gaming.',
                        'Afternoon grind 🤓 compile fail. Snack time.',
                        'Afternoon grind ⚙️ compile fail. Keep gaming.',
                        'Afternoon grind 📚 LAN prep. Keep gaming.',
                        'Afternoon grind 💻 compile fail. Next quest.',
                        'Afternoon grind 🤓 snack stash. Keep gaming.',
                        'Afternoon grind 💻 compile fail. Next quest.',
                        'Afternoon grind 🤓 stack overflow. Snack time.',
                        'Afternoon grind 🤓 stack overflow. Next quest.',
                        'Afternoon grind 🎮 stack overflow. Snack time.',
                        'Afternoon grind 📚 snack stash. Keep gaming.',
                        'Afternoon grind 💻 stack overflow. Keep gaming.',
                        'Afternoon grind 🤓 snack stash. Keep gaming.',
                        'Afternoon grind 📚 snack stash. Next quest.',
                        'Afternoon grind 📚 dice roll. Next quest.',
                        'Afternoon grind 🤓 snack stash. Snack time.',
                        'Afternoon grind 📚 stack overflow. Next quest.',
                        'Afternoon grind 📚 snack stash. Snack time.',
                        'Afternoon grind 💻 dice roll. Next quest.',
                        'Afternoon grind 🤓 stack overflow. Keep gaming.',
                        'Afternoon grind 📚 LAN prep. Next quest.',
                        'Afternoon grind ⚙️ compile fail. Snack time.',
                        'Afternoon grind 📚 dice roll. Next quest.',
                        'Afternoon grind 🎮 dice roll. Keep gaming.',
                        'Afternoon grind ⚙️ stack overflow. Snack time.',
                        'Afternoon grind 🤓 compile fail. Snack time.',
                        'Afternoon grind ⚙️ snack stash. Snack time.',
                        'Afternoon grind 💻 compile fail. Keep gaming.',
                        'Afternoon grind 💻 stack overflow. Snack time.',
                        'Afternoon grind 🤓 stack overflow. Snack time.',
                        'Afternoon grind 💻 stack overflow. Keep gaming.',
                        'Afternoon grind 🎮 snack stash. Keep gaming.',
                        'Afternoon grind ⚙️ compile fail. Next quest.',
                        'Afternoon grind 💻 compile fail. Next quest.',
                        'Afternoon grind ⚙️ snack stash. Snack time.',
                        'Afternoon grind 💻 stack overflow. Keep gaming.',
                        'Afternoon grind ⚙️ LAN prep. Next quest.',
                        'Afternoon grind ⚙️ compile fail. Keep gaming.',
                        'Afternoon grind 🤓 dice roll. Keep gaming.',
                        'Afternoon grind 📚 LAN prep. Next quest.',
                        'Afternoon grind 🤓 stack overflow. Snack time.',
                        'Afternoon grind 📚 LAN prep. Snack time.'],
          'evening': ['Evening raid 🤓 raid squad. Stay nerdy.',
                      'Evening raid 🎮 code spree. Achievement unlocked.',
                      'Evening raid 💻 raid squad. Stay nerdy.',
                      'Evening raid 📚 debug session. Achievement unlocked.',
                      'Evening raid 📚 pizza patch. Level up.',
                      'Evening raid 🤓 raid squad. Achievement unlocked.',
                      'Evening raid 📚 raid squad. Stay nerdy.',
                      'Evening raid 💻 raid squad. Achievement unlocked.',
                      'Evening raid 🎮 pizza patch. Level up.',
                      'Evening raid 💻 code spree. Level up.',
                      'Evening raid 📚 code spree. Stay nerdy.',
                      'Evening raid ⚙️ debug session. Stay nerdy.',
                      'Evening raid 🤓 game queue. Stay nerdy.',
                      'Evening raid 🎮 raid squad. Achievement unlocked.',
                      'Evening raid ⚙️ raid squad. Level up.',
                      'Evening raid 🎮 debug session. Stay nerdy.',
                      'Evening raid 📚 game queue. Achievement unlocked.',
                      'Evening raid ⚙️ code spree. Achievement unlocked.',
                      'Evening raid 🤓 raid squad. Achievement unlocked.',
                      'Evening raid 🤓 debug session. Stay nerdy.',
                      'Evening raid 💻 debug session. Stay nerdy.',
                      'Evening raid 🎮 code spree. Achievement unlocked.',
                      'Evening raid 🎮 pizza patch. Level up.',
                      'Evening raid 🎮 debug session. Achievement unlocked.',
                      'Evening raid 📚 debug session. Stay nerdy.',
                      'Evening raid ⚙️ pizza patch. Stay nerdy.',
                      'Evening raid 💻 debug session. Achievement unlocked.',
                      'Evening raid 🤓 game queue. Level up.',
                      'Evening raid 💻 debug session. Level up.',
                      'Evening raid 📚 code spree. Achievement unlocked.',
                      'Evening raid 💻 debug session. Stay nerdy.',
                      'Evening raid 💻 pizza patch. Level up.',
                      'Evening raid ⚙️ game queue. Achievement unlocked.',
                      'Evening raid 💻 raid squad. Stay nerdy.',
                      'Evening raid ⚙️ game queue. Level up.',
                      'Evening raid 💻 game queue. Level up.',
                      'Evening raid 🎮 pizza patch. Stay nerdy.',
                      'Evening raid 🎮 game queue. Achievement unlocked.',
                      'Evening raid 🤓 pizza patch. Stay nerdy.',
                      'Evening raid 💻 debug session. Achievement unlocked.',
                      'Evening raid 📚 debug session. Stay nerdy.',
                      'Evening raid ⚙️ pizza patch. Level up.',
                      'Evening raid 📚 raid squad. Achievement unlocked.',
                      'Evening raid ⚙️ raid squad. Achievement unlocked.',
                      'Evening raid 🎮 raid squad. Achievement unlocked.',
                      'Evening raid 💻 debug session. Level up.',
                      'Evening raid 📚 debug session. Level up.',
                      'Evening raid 🎮 game queue. Stay nerdy.',
                      'Evening raid 🎮 code spree. Level up.',
                      'Evening raid 🎮 pizza patch. Stay nerdy.'],
          'morning': ['Boot sequence ⚙️ quest begin. Ready?',
                      'Boot sequence ⚙️ respawn. Ready?',
                      'Boot sequence 📚 quest begin. Error 404 energy.',
                      'Boot sequence 🤓 loading coffee.exe. Ready?',
                      'Boot sequence ⚙️ quest begin. Let’s code.',
                      'Boot sequence ⚙️ respawn. Error 404 energy.',
                      'Boot sequence ⚙️ loading coffee.exe. Error 404 energy.',
                      'Boot sequence 🤓 debugging alarm. Error 404 energy.',
                      'Boot sequence ⚙️ debugging alarm. Ready?',
                      'Boot sequence 📚 quest begin. Let’s code.',
                      'Boot sequence 🤓 debugging alarm. Let’s code.',
                      'Boot sequence 💻 debugging alarm. Let’s code.',
                      'Boot sequence 🎮 patch brain. Error 404 energy.',
                      'Boot sequence 🤓 loading coffee.exe. Ready?',
                      'Boot sequence 🤓 quest begin. Error 404 energy.',
                      'Boot sequence ⚙️ respawn. Error 404 energy.',
                      'Boot sequence 🤓 patch brain. Error 404 energy.',
                      'Boot sequence 📚 quest begin. Let’s code.',
                      'Boot sequence 🎮 loading coffee.exe. Let’s code.',
                      'Boot sequence ⚙️ respawn. Error 404 energy.',
                      'Boot sequence 💻 quest begin. Error 404 energy.',
                      'Boot sequence 📚 loading coffee.exe. Error 404 energy.',
                      'Boot sequence 🤓 debugging alarm. Error 404 energy.',
                      'Boot sequence 💻 loading coffee.exe. Let’s code.',
                      'Boot sequence 💻 loading coffee.exe. Ready?',
                      'Boot sequence 📚 respawn. Error 404 energy.',
                      'Boot sequence 🤓 patch brain. Ready?',
                      'Boot sequence 💻 quest begin. Error 404 energy.',
                      'Boot sequence 📚 respawn. Error 404 energy.',
                      'Boot sequence 🎮 loading coffee.exe. Let’s code.',
                      'Boot sequence 🎮 respawn. Ready?',
                      'Boot sequence ⚙️ debugging alarm. Error 404 energy.',
                      'Boot sequence 🎮 quest begin. Error 404 energy.',
                      'Boot sequence 📚 loading coffee.exe. Ready?',
                      'Boot sequence 🤓 respawn. Let’s code.',
                      'Boot sequence 🤓 debugging alarm. Error 404 energy.',
                      'Boot sequence 🎮 quest begin. Ready?',
                      'Boot sequence 🤓 respawn. Error 404 energy.',
                      'Boot sequence 🤓 patch brain. Let’s code.',
                      'Boot sequence 📚 loading coffee.exe. Error 404 energy.',
                      'Boot sequence 📚 patch brain. Let’s code.',
                      'Boot sequence 🎮 loading coffee.exe. Error 404 energy.',
                      'Boot sequence 🤓 loading coffee.exe. Ready?',
                      'Boot sequence 🤓 loading coffee.exe. Let’s code.',
                      'Boot sequence 💻 patch brain. Let’s code.',
                      'Boot sequence 📚 patch brain. Let’s code.',
                      'Boot sequence ⚙️ debugging alarm. Ready?',
                      'Boot sequence 🎮 patch brain. Error 404 energy.',
                      'Boot sequence 💻 loading coffee.exe. Let’s code.',
                      'Boot sequence 📚 patch brain. Error 404 energy.'],
          'night': ['Night mode 💻 LAN vibes. Sleep = optional.',
                    'Night mode 🎮 fan noise. Sleep = optional.',
                    'Night mode ⚙️ binary dreams. Sleep = optional.',
                    'Night mode 💻 binary dreams. Game on.',
                    'Night mode ⚙️ fan noise. Sleep = optional.',
                    'Night mode 💻 LAN vibes. Night owl engaged.',
                    'Night mode 🤓 late coffee. Night owl engaged.',
                    'Night mode ⚙️ debug loop. Night owl engaged.',
                    'Night mode 🤓 late coffee. Game on.',
                    'Night mode 📚 debug loop. Sleep = optional.',
                    'Night mode 📚 fan noise. Sleep = optional.',
                    'Night mode 🎮 LAN vibes. Game on.',
                    'Night mode 🤓 binary dreams. Game on.',
                    'Night mode ⚙️ binary dreams. Game on.',
                    'Night mode 💻 fan noise. Game on.',
                    'Night mode 💻 debug loop. Night owl engaged.',
                    'Night mode 🎮 debug loop. Night owl engaged.',
                    'Night mode 🤓 late coffee. Game on.',
                    'Night mode 📚 debug loop. Game on.',
                    'Night mode ⚙️ fan noise. Sleep = optional.',
                    'Night mode ⚙️ LAN vibes. Sleep = optional.',
                    'Night mode 💻 fan noise. Game on.',
                    'Night mode 🎮 binary dreams. Sleep = optional.',
                    'Night mode 💻 debug loop. Night owl engaged.',
                    'Night mode 💻 debug loop. Night owl engaged.',
                    'Night mode 📚 late coffee. Game on.',
                    'Night mode 🤓 late coffee. Game on.',
                    'Night mode 🤓 debug loop. Night owl engaged.',
                    'Night mode 🎮 late coffee. Sleep = optional.',
                    'Night mode 💻 debug loop. Sleep = optional.',
                    'Night mode ⚙️ binary dreams. Game on.',
                    'Night mode 💻 late coffee. Game on.',
                    'Night mode 💻 binary dreams. Game on.',
                    'Night mode 💻 fan noise. Game on.',
                    'Night mode 🤓 binary dreams. Night owl engaged.',
                    'Night mode 💻 fan noise. Game on.',
                    'Night mode 💻 binary dreams. Sleep = optional.',
                    'Night mode 💻 LAN vibes. Sleep = optional.',
                    'Night mode 🤓 binary dreams. Sleep = optional.',
                    'Night mode 🎮 late coffee. Night owl engaged.',
                    'Night mode 💻 debug loop. Night owl engaged.',
                    'Night mode 🤓 debug loop. Night owl engaged.',
                    'Night mode 🎮 fan noise. Sleep = optional.',
                    'Night mode 💻 LAN vibes. Sleep = optional.',
                    'Night mode 🎮 binary dreams. Night owl engaged.',
                    'Night mode ⚙️ binary dreams. Game on.',
                    'Night mode 📚 fan noise. Sleep = optional.',
                    'Night mode 💻 debug loop. Game on.',
                    'Night mode 🤓 debug loop. Game on.',
                    'Night mode ⚙️ debug loop. Night owl engaged.']},
 'neutral': {'afternoon': ['Afternoon check-in ☀️ routine intact.',
                           'Afternoon check-in 🙂 balance mode.',
                           'Afternoon check-in 🌙 simple vibe.',
                           'Afternoon check-in 🙂 routine intact.',
                           'Afternoon check-in 🌙 simple vibe.',
                           'Afternoon check-in ✅ simple vibe.',
                           'Afternoon check-in 📘 simple vibe.',
                           'Afternoon check-in ✅ steady day.',
                           'Afternoon check-in ☀️ steady day.',
                           'Afternoon check-in 🌙 balance mode.',
                           'Afternoon check-in 📘 calm start.',
                           'Afternoon check-in ☀️ balance mode.',
                           'Afternoon check-in ☀️ steady day.',
                           'Afternoon check-in ✅ balance mode.',
                           'Afternoon check-in 📘 calm start.',
                           'Afternoon check-in ☀️ calm start.',
                           'Afternoon check-in ☀️ balance mode.',
                           'Afternoon check-in ✅ balance mode.',
                           'Afternoon check-in 🌙 steady day.',
                           'Afternoon check-in 🌙 simple vibe.',
                           'Afternoon check-in 🙂 calm start.',
                           'Afternoon check-in 📘 calm start.',
                           'Afternoon check-in ☀️ calm start.',
                           'Afternoon check-in ✅ calm start.',
                           'Afternoon check-in 🙂 steady day.',
                           'Afternoon check-in ☀️ balance mode.',
                           'Afternoon check-in 🙂 calm start.',
                           'Afternoon check-in 🌙 balance mode.',
                           'Afternoon check-in 🌙 steady day.',
                           'Afternoon check-in 🙂 calm start.',
                           'Afternoon check-in 🙂 calm start.',
                           'Afternoon check-in 📘 simple vibe.',
                           'Afternoon check-in ☀️ steady day.',
                           'Afternoon check-in 🙂 simple vibe.',
                           'Afternoon check-in 📘 simple vibe.',
                           'Afternoon check-in 🌙 steady day.',
                           'Afternoon check-in 🙂 balance mode.',
                           'Afternoon check-in 🌙 balance mode.',
                           'Afternoon check-in ☀️ steady day.',
                           'Afternoon check-in ✅ steady day.',
                           'Afternoon check-in 🌙 calm start.',
                           'Afternoon check-in ☀️ balance mode.',
                           'Afternoon check-in 📘 simple vibe.',
                           'Afternoon check-in ✅ simple vibe.',
                           'Afternoon check-in 🌙 calm start.',
                           'Afternoon check-in 📘 steady day.',
                           'Afternoon check-in 📘 simple vibe.',
                           'Afternoon check-in ☀️ calm start.',
                           'Afternoon check-in ✅ calm start.',
                           'Afternoon check-in 🌙 simple vibe.'],
             'evening': ['Evening check-in 🙂 balance mode.',
                         'Evening check-in 🌙 balance mode.',
                         'Evening check-in 🌙 steady day.',
                         'Evening check-in 🌙 routine intact.',
                         'Evening check-in 🙂 balance mode.',
                         'Evening check-in ✅ steady day.',
                         'Evening check-in 📘 simple vibe.',
                         'Evening check-in 🙂 steady day.',
                         'Evening check-in 🙂 routine intact.',
                         'Evening check-in 📘 steady day.',
                         'Evening check-in ✅ steady day.',
                         'Evening check-in 📘 simple vibe.',
                         'Evening check-in ☀️ calm start.',
                         'Evening check-in ✅ simple vibe.',
                         'Evening check-in 🙂 balance mode.',
                         'Evening check-in ☀️ balance mode.',
                         'Evening check-in 📘 balance mode.',
                         'Evening check-in ☀️ routine intact.',
                         'Evening check-in 🌙 balance mode.',
                         'Evening check-in 🙂 calm start.',
                         'Evening check-in ✅ simple vibe.',
                         'Evening check-in 🌙 routine intact.',
                         'Evening check-in 🌙 steady day.',
                         'Evening check-in 🌙 simple vibe.',
                         'Evening check-in ✅ steady day.',
                         'Evening check-in ✅ routine intact.',
                         'Evening check-in 📘 simple vibe.',
                         'Evening check-in 🌙 calm start.',
                         'Evening check-in 🌙 simple vibe.',
                         'Evening check-in 🙂 routine intact.',
                         'Evening check-in ☀️ steady day.',
                         'Evening check-in 🌙 calm start.',
                         'Evening check-in 🌙 simple vibe.',
                         'Evening check-in 🌙 balance mode.',
                         'Evening check-in 📘 simple vibe.',
                         'Evening check-in ☀️ routine intact.',
                         'Evening check-in 🙂 simple vibe.',
                         'Evening check-in ✅ simple vibe.',
                         'Evening check-in ☀️ calm start.',
                         'Evening check-in 📘 steady day.',
                         'Evening check-in 📘 steady day.',
                         'Evening check-in 🌙 calm start.',
                         'Evening check-in 🙂 calm start.',
                         'Evening check-in ✅ calm start.',
                         'Evening check-in 🙂 routine intact.',
                         'Evening check-in 📘 simple vibe.',
                         'Evening check-in 🌙 calm start.',
                         'Evening check-in ☀️ simple vibe.',
                         'Evening check-in ☀️ steady day.',
                         'Evening check-in ✅ routine intact.'],
             'morning': ['Morning check-in 🌙 calm start.',
                         'Morning check-in 📘 steady day.',
                         'Morning check-in ✅ steady day.',
                         'Morning check-in ☀️ routine intact.',
                         'Morning check-in ✅ balance mode.',
                         'Morning check-in 🌙 routine intact.',
                         'Morning check-in ✅ calm start.',
                         'Morning check-in 📘 calm start.',
                         'Morning check-in 🙂 routine intact.',
                         'Morning check-in 🙂 routine intact.',
                         'Morning check-in 🌙 steady day.',
                         'Morning check-in 📘 balance mode.',
                         'Morning check-in ✅ simple vibe.',
                         'Morning check-in 📘 steady day.',
                         'Morning check-in 🌙 routine intact.',
                         'Morning check-in 🌙 simple vibe.',
                         'Morning check-in ✅ simple vibe.',
                         'Morning check-in 🙂 balance mode.',
                         'Morning check-in 🌙 steady day.',
                         'Morning check-in ☀️ steady day.',
                         'Morning check-in 🌙 steady day.',
                         'Morning check-in 📘 balance mode.',
                         'Morning check-in 🙂 routine intact.',
                         'Morning check-in 🙂 balance mode.',
                         'Morning check-in 📘 balance mode.',
                         'Morning check-in 🌙 steady day.',
                         'Morning check-in 🙂 steady day.',
                         'Morning check-in ☀️ calm start.',
                         'Morning check-in 🙂 calm start.',
                         'Morning check-in ✅ simple vibe.',
                         'Morning check-in 🌙 simple vibe.',
                         'Morning check-in 📘 balance mode.',
                         'Morning check-in 🌙 balance mode.',
                         'Morning check-in 🙂 calm start.',
                         'Morning check-in 📘 steady day.',
                         'Morning check-in ✅ simple vibe.',
                         'Morning check-in ✅ routine intact.',
                         'Morning check-in 📘 calm start.',
                         'Morning check-in ☀️ routine intact.',
                         'Morning check-in 🌙 routine intact.',
                         'Morning check-in ☀️ balance mode.',
                         'Morning check-in 🌙 simple vibe.',
                         'Morning check-in 🙂 balance mode.',
                         'Morning check-in 🌙 steady day.',
                         'Morning check-in ✅ balance mode.',
                         'Morning check-in 🙂 routine intact.',
                         'Morning check-in 🌙 balance mode.',
                         'Morning check-in ☀️ steady day.',
                         'Morning check-in 📘 routine intact.',
                         'Morning check-in 🙂 calm start.'],
             'night': ['Night check-in 📘 routine intact.',
                       'Night check-in 📘 steady day.',
                       'Night check-in 📘 calm start.',
                       'Night check-in 🙂 balance mode.',
                       'Night check-in 🙂 steady day.',
                       'Night check-in 🙂 routine intact.',
                       'Night check-in ☀️ simple vibe.',
                       'Night check-in ✅ calm start.',
                       'Night check-in ✅ routine intact.',
                       'Night check-in ☀️ steady day.',
                       'Night check-in 📘 calm start.',
                       'Night check-in ☀️ balance mode.',
                       'Night check-in 📘 balance mode.',
                       'Night check-in 📘 balance mode.',
                       'Night check-in 🌙 calm start.',
                       'Night check-in 🌙 balance mode.',
                       'Night check-in ✅ routine intact.',
                       'Night check-in 🌙 balance mode.',
                       'Night check-in 🌙 simple vibe.',
                       'Night check-in ✅ calm start.',
                       'Night check-in 🌙 balance mode.',
                       'Night check-in ✅ balance mode.',
                       'Night check-in 🙂 simple vibe.',
                       'Night check-in 🌙 steady day.',
                       'Night check-in ✅ balance mode.',
                       'Night check-in 🙂 steady day.',
                       'Night check-in 🌙 routine intact.',
                       'Night check-in ✅ steady day.',
                       'Night check-in ☀️ routine intact.',
                       'Night check-in 🙂 steady day.',
                       'Night check-in 📘 steady day.',
                       'Night check-in 🙂 steady day.',
                       'Night check-in ✅ balance mode.',
                       'Night check-in 🙂 steady day.',
                       'Night check-in 🙂 calm start.',
                       'Night check-in 📘 steady day.',
                       'Night check-in 🌙 calm start.',
                       'Night check-in 📘 routine intact.',
                       'Night check-in ☀️ routine intact.',
                       'Night check-in 📘 balance mode.',
                       'Night check-in 📘 steady day.',
                       'Night check-in 🌙 simple vibe.',
                       'Night check-in 📘 balance mode.',
                       'Night check-in ✅ calm start.',
                       'Night check-in ✅ routine intact.',
                       'Night check-in 🌙 calm start.',
                       'Night check-in 🙂 steady day.',
                       'Night check-in ☀️ steady day.',
                       'Night check-in 🙂 balance mode.',
                       'Night check-in 📘 balance mode.']}}


def pick_persona_line(persona: str, time_of_day: str) -> str:
    lines = PERSONALITIES.get(persona, {}).get(time_of_day, [])
    if not lines:
        return ''
    return random.choice(lines)
