name: PicoTTS
version: 1.6.0
slug: picotts
description: Text to speech voice synthesizer from SVox, included in Android AOSP.
url: https://github.com/Poeschl/Hassio-Addons/tree/main/picoTTS
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.io/poeschl/ha-picotts-{arch}
init: false
ports:
  59126/tcp: 59126
ports_description:
  59126/tcp: Http interface of the REST wrapper
