---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:6.1.2
  amd64: ghcr.io/hassio-addons/debian-base:6.1.2
  armv7: ghcr.io/hassio-addons/debian-base:6.1.2
codenotary:
  signer: alexandrep.github@gmail.com
