---
name: Mimic Mycroft TTS Server
version: 0.0.1
slug: mimictts
description: Mimic - The Mycroft TTS Engine
url: https://mimic.mycroft.ai/
codenotary: bothmacell@gmail.com
arch:
- armv7
- aarch64
- amd64
init: false
ports:
  59125/tcp: 59125
ports_description:
  59125/tcp: Mimic Webui
 map: 
   - config:rw
   - share:rw
privileged:
   - SYS_ADMIN
   - DAC_READ_SEARCH
   - NET_ADMIN
   
