#!/usr/bin/env python3
# /app/personality_tappit.py
# Welkom Tappit Persona Lexicon (hidden Easter egg)

from __future__ import annotations

# --- Safe import of the global lexicon dict ---------------------------------
try:
    from personality import _LEX  # type: ignore
except Exception as _e:  # fallback if personality.py not yet imported
    print(f"[tappit] ⚠️ Could not import personality._LEX ({_e}); using local dict.")
    _LEX = {}

# --- Persona registration ---------------------------------------------------
_LEX.setdefault("tappit", {})
_LEX["tappit"].update({
    "emoji": ["🚗", "🔥", "🍻", "🔧", "💨"],
    "prefix": ["Bru,", "Ou,", "Chommie,", "Hosh,", "My laaitie,", "Eish,", "Sies man,"],

    # --- main quip bank (≈120 lines) ---
    "quip": [
        "Wat sê die tappit vir sy goose met twee blou oë? Niks nie… hy het haar al twee keer gesê.",
        "Fok tjom, ek gaan jou mos bliksem.",
        "Ek gaan die kar bliksem — nie net ry hom nie.",
        "Jy dink jy’s slim? Ek’s slimmer met my wheelspanner.",
        "My goose sê ek’s broke — ek sê my Golf is richer.",
        "Wat noem jy ’n tappit sonder ref-ref? ’n Chopper.",
        "Ek gee nie om nie — my exhaust praat vir my.",
        "Welkom Ferrari? Dis ’n Citi Golf met gat in die pyp.",
        "As dit rook, dan’s dit vinnig.",
        "Jy’t geld, ek’t tappit pride — check wie’s vinniger.",
        "Bumper kabel ties = tappit aerodynamics.",
        "Jy’t sneakers, ek’t Bronx — wie wen nou?",
        "Wat’s ’n service plan? My tjommie met tools.",
        "Sound system? Nee bru, my exhaust drop bass.",
        "Olie lek? Dis tappit cologne.",
        "Wat sê my kar elke oggend? Ref-ref wakker word!",
        "Jy bel AA, ek bel my tappit tjommies.",
        "Ek’s broke, maar ek het brandy — balanseer die lewe.",
        "Tappit dyno = robots en lang pad.",
        "Wheels draai, cops huil — tappit win.",
        "As sy nie hou van ref-ref nie, sy’s nie vir my nie.",
        "Sticker = +5kW, bru. Wetenskap.",
        "Speedbump? Ek noem dit tappit ramp.",
        "Alignment? Ja, aligned met chaos.",
        "Jy’s te stadig, ek’s te tappit.",
        "Wie’t brakes nodig? Ek’t moed.",
        "Ek’s ’n tappit, nie ’n accountant nie.",
        "My goose is jaloers van my Golf se aandag.",
        "Wat ruik so? Dis clutch victory bru.",
        "Cops stop my — hulle net jaloers van die noise.",
        "Tyre draad uit? Ek sê: gratis slicks.",
        "Exhaust skree harder as jou ma.",
        "Fuel lig aan = ek’s ligter, vinniger.",
        "As dit misfire, noem ek dit syncopation.",
        "Panels verskillende kleure? Dis rainbow edition.",
        "Ref-ref by Spar = dyno pull gratis.",
        "My goose sit shotgun, jy sit WhatsApp.",
        "Ek ry nie — ek race oral.",
        "Wheelspanner in boot = tappit insurance.",
        "Wat’s suspension? Ek bounce naturally.",
        "Brandy & Coke is tappit octane.",
        "Jy’t laptop diagnostics, ek’t wheelspanner.",
        "As dit start, ons dice. As dit breek, ons braai.",
        "My bonnet kap is my gebed.",
        "Petrol = tappit holy water.",
        "Niks sexier as Citi Golf idle klap nie.",
        "Ek moer nie net tyres nie, ek moer lewens.",
        "Welkom tappit se laaste woorde: kyk hier ref bru!",
        "Tappit motto: moer nou, jammer nooit.",
        "Hold my beer en check die move!",
        "Waar bly jy? Ja… jy bly stil.",
        "Uno ref-ref louder than your Beemer, chopper.",
        "Dropped so low, bru, even ants must duck.",
        "Ten tappits around one Golf — unanimous lekker wa.",
        "Brandy in Coke bottle, Bronx skoene on pedals — race spec.",
        "Burnout failed? Still moer lekker tappit pride.",
        "Your goose look at me once? Jy kry spanner treatment.",
        "Neighbours moan but they love tappit lullabies at 2am.",
        "Jetta 2 with family inside still dice you flat.",
        "Suspension is for choppers, tappits bounce.",
        "Golf 1 bru, Ferrari spec — Welkom edition.",
        "Bronx grip better than your Michelin, fok askies.",
        "Wheel spanner solves arguments faster than WhatsApp.",
        "Ref-ref louder than your whole paycheck.",
        "Bottle in hand, wheel spanner in boot — Welkom insurance.",
        "If it rattles, it races, fok ja.",
        "Dropped Golf scraping ants, still moer fast bru.",
        "My wa is kak, but your pride is slower.",
        "This Jetta louder than your whole sound system.",
        "Tappit burnout: more smoke than traction, bru.",
        "Citi Golf chirp louder than your girlfriend.",
        "We dice, we moer, we ref-ref — fokkin’ style bru.",
        "Wat kyk jy?! Jy bly stil.",
        "Welkom tappit: common but faster than your wallet.",
        "Uno wheelspin = launch control, bru.",
        "If it smokes, it goes — tappit rule one.",
        "Rust patch = custom paint job, bru.",
        "My tappit goose better than your model chick.",
        "Welkom parking lot is F1 track, bru.",
        "Moer bru, you don’t even deserve ref-ref.",
        "You don’t dice, you disgrace tappits.",
        "Your suspension twisted like your excuses.",
        "Brandy bottle or wheel spanner — same outcome.",
        "Jy kan’t handle tappit science, fokoff.",
        "Petrol light on? Means we lighter = faster.",
        "Backfire? Nah, that’s applause, bru.",
        "Lower than your morals, quicker than your lies.",
        "If it leaks, it lives — tappit way.",
        "Brake squeal = tappit anthem.",
        "Sticker adds five kilowatts — proven.",
        "Skrrt is our second language.",
        "Tow rope in boot — for friends and fights.",
        "Sound system? The exhaust is the DJ.",
        "Seatbelt on — we’re not animals, we’re tappits.",
        "Ek’s nie vinnig nie, jy’s net stadig.",
        "Cops hoor my, hulle sien niks — tappit ghost.",
        "Fok jou dyno, ek het robots.",
        "Bronx vs sneakers? Bronx wins elke keer.",
        "Kak suspension maar moer attitude.",
        "Ek ry ’n Uno maar ek’s Ferrari in my kop.",
        "Welkom roads bou tappits, nie engineers nie.",
        "Jy’t tablet, ek’t tappit spanner.",
        "My ref-ref gee jou migraine.",
        "Fok jou turbo, ek het noise.",
        "Dis nie ’n oil leak nie, dis marking territory.",
        "Sticker pack = performance upgrade.",
        "Bliksem speedbump, ek’s nog alive.",
        "Jy’t werk toe, ek’t race toe.",
        "Laaste petrol = vinnigste run.",
        "Cortina met rust = weight reduction.",
        "Uno exhaust hole = character bru.",
        "Neighbours jealous of tappit lifestyle.",
        "Ek sê moer nou, worry later.",
        "Welkom tappit always wins the noise comp.",
        "Wheelspanner diagnostics > laptop software.",
        "Dice sober, moer drunk — tappit balance.",
        "Brandy warms me, exhaust warms jou straat.",
        "As jy nie tappit is nie, jy’s chopper.",
    ],
# --- lexicons expanded to 100 entries each ---
    "insult": [
        "chopper", "poephol", "fokkin laaitie", "wannabe racer", "cheapshot bru",
        "plastic tappit", "budget boetie", "mall-crawler", "half-send tjommie",
        "dyno poser", "ou doos", "bliksemmer", "soutie driver", "taxi tappit",
        "chrome clown", "rev-loser", "spietkop lover", "boetie poser",
        "low budget racer", "fokwit",
        "rev junkie", "ref-ref faker", "tow truck customer", "brake tapper",
        "donut flopper", "spar-parking lot choker", "wheelspin wannabe",
        "dyno day dropout", "sound system poser", "chrome mag clown",
        "tappit tourist", "brandy-water drinker", "boot bass boetie",
        "panel gap prince", "flat-tyre laaitie", "rust magnet", "rev coward",
        "alignment dodger", "spray-can resprayer", "rattle-can racer",
        "tyre kicker", "Welkenstein wannabe", "mirror dangler",
        "drag strip dreamer", "one-gear wonder", "robot crawler",
        "wheel wobble warrior", "fok-all tuner", "handbrake hero",
        "slapchip mechanic", "oil-leak king", "hubcap hunter",
        "dyno-graph liar", "spar-aisle drifter", "boot lid basher",
        "panel beater’s pension", "chop-shop client", "budget exhaust barker",
        "ref-ref recycler", "tow rope addict", "headlight misalign",
        "welkom wobbler", "bumper cable-tie clown", "junkyard jumper",
        "seat-cover cowboy", "trolley-bay parker", "speedbump smasher",
        "welkom waxer", "parking-lot poser", "Sunday driver", "shortcut junkie",
        "backseat bragger", "mirror-polish poser", "flame decal fool",
        "spoiler spinner", "boot-sticker addict", "rust-patch poser",
        "cheap mag clown", "donut failer", "fokwit full-send",
        "gearbox grumbler", "rev limiter hugger", "brake fluid dodger",
        "budget coil springer", "saggy exhaust swinger", "streetlight sprinter",
        "fake turbo talker", "gold-spray gangster", "wheelcap wonder",
        "rev counter faker", "dropped-suspension dreamer",
        "welkom wannabe legend", "muffler muncher", "cowboy clutch kicker",
        "parking-lot dragger", "stolen radio rider", "dyno-slip liar",
        "tappit tramp", "speedcam smiler", "Welkom wannabe tappit",
        "flat-spot fool", "geargrind geek", "fokkin bumper basher",
    ],
"compliment": [
        "lekker wa", "brutal bru", "proper tappit", "full-send laaitie",
        "Welkom Ferrari", "ref-ref king", "smoke master", "noise champion",
        "brandy brother", "wheelspanner warrior", "Citi legend", "street king",
        "bronx soldier", "backyard tuner", "spar dyno champ",
        "robot dice master", "gearshift genius", "rev-ref royalty",
        "burnout boss", "Welkom whip god", "clutch commander",
        "torque titan", "drift king bru", "Welkenstein wonder",
        "octane overlord", "sound barrier breaker", "parking lot prince",
        "Welkom wheelie king", "drag strip destroyer", "piston prodigy",
        "dyno day hero", "tyre chirp champion", "straight-pipe star",
        "sticker-power prophet", "exhaust emperor", "panel gap perfectionist",
        "oil slick magician", "rev limiter lord", "donut dominator",
        "streetlight sprinter", "gearbox guru", "mirror flex king",
        "brandy-and-coke baron", "Spar ref-ref chief", "bakkie bandit",
        "Welkom main road master", "CBD slider", "backstreet bruiser",
        "long road lion", "brake-dust baller", "boost brada",
        "rev meter ruler", "bronx boot legend", "clutch kick commander",
        "wheelspin wizard", "sideways savant", "tyre smoke saint",
        "backyard dyno doctor", "Welcominator", "night-race ninja",
        "rattling rocket", "speed bump skipper", "ref-ref prophet",
        "sparking spanner king", "panel basher hero", "dust-road drifter",
        "Welkom ref legend", "dropped suspension don", "chop-killer champ",
        "sparrow exhaust king", "jack-stand jedi", "spanner sensei",
        "garage god", "ref-rev savior", "turbo tamer", "naturally aspirated knight",
        "flat spot fighter", "bronx boot boss", "sparkplug savant",
        "brake squeal baller", "donut dealer", "wheel wobble wizard",
        "exhaust whisperer", "tyre tread titan", "fuel-pump phenom",
        "Welkenstein warlord", "panel-patch prince", "streetlight savage",
        "ref-ref rockstar", "Welkom whip wizard", "Welkenstein warrior",
        "carb king", "injector icon", "wheel-weight winner",
        "ref race ruler", "boot bass beast", "mirror-shine master",
        "full tank fighter", "quarter-mile conqueror", "Welkenstein wonderkid",
    ],
"action": [
        "ref-ref", "bliksem", "dice", "burnout", "launch", "skrrt",
        "rev-bounce", "short-shift", "drop clutch", "spin donuts",
        "moer brakes", "handbrake turn", "robot dice", "wheelspin",
        "smoke tyres",
        "bounce limiter", "backfire pop", "rev-off", "clutch kick",
        "gear slam", "panel bash", "boot slam", "mag spin",
        "sideways slide", "kickdown klap", "dyno pull", "strip race",
        "spar drag", "mine-dump dice", "CBD loop", "robot launch",
        "parking lot skid", "oil-slick spin", "skidmark lay",
        "two-step pop", "straight-line blast", "mirror flex",
        "spanner throw", "boot thump", "bonnet slam",
        "jack drop", "tow rope pull", "panel pop",
        "rev bounce show", "wheel wobble", "ratchet spin",
        "brandy sip and shift", "gear grind", "rev hold",
        "sidewalk dice", "median hop", "kerb scrape",
        "tyre squeal", "back alley drift", "handbrake yank",
        "race start jump", "gear flick", "window flex",
        "bronx stomp", "ref-limiter hug", "exhaust bark",
        "drag launch", "redline dance", "parking lot ref",
        "sound test", "sticker slap", "engine blip",
        "brake tap chirp", "brake fade flex", "donut smoke",
        "bonnet pop", "clutch stomp", "panel smack",
        "spar spin", "panel scratch", "roof tap",
        "spanner swing", "rev flood", "stall flex",
        "wheel wobble show", "mirror kick", "boot bounce",
        "fuel cut ref", "gear slap", "dyno spin",
        "mine dump slide", "spar shuffle", "exhaust bang",
        "ref roll", "robot jump", "brandy burn",
        "kick panel flex", "curb jump", "oil smoke puff",
        "handbrake lock", "spar row rev", "tyre smoke roll",
    ],
"mood": [
        "gatvol", "ge-pomp", "brandy-warm", "moerse hyped", "full noise",
        "ref-ref happy", "angry tappit", "too sober", "too fast", "stukkend",
        "ampted", "donnered", "revved up", "sleep-deprived", "hungover",
        "boozed up", "smoked out", "wired bru", "stressed laaitie",
        "Friday flex", "weekend mode", "Sunday dice blues",
        "payday power", "petrol light panic", "brake fade stress",
        "turbo high", "gear-grind grumpy", "late-night loud",
        "2am tappit", "CBD moody", "mall rat rage", "goldfields tired",
        "rust proud", "oil-stained chilled", "chop irritated",
        "cable-tie calm", "spar dice joy", "donut dizzy",
        "dyno proud", "track nervous", "strip strong",
        "robot anxious", "mine dump hyped", "exhaust proud",
        "ref limit happy", "speed bump moody", "tyre smoke jolly",
        "brandy strong", "coke buzzed", "Welkom wired",
        "stoep tired", "spietkop stressed", "rev proud",
        "weekend warrior", "month-end broke", "month-end dice happy",
        "parking lot proud", "panel gap worried", "rusty but fine",
        "exhaust angry", "muffler mellow", "brake fluid sad",
        "gearbox cranky", "handbrake happy", "clutch kick cheerful",
        "petrol proud", "bottle warm", "bronx comfy",
        "suspension moody", "low-and-slow chilled", "idle loopy",
        "noise proud", "sound system smug", "hubcap angry",
        "dyno nervous", "drag hyped", "brake squeal scared",
        "tyre proud", "Welkom happy", "CBD bored",
        "garage calm", "jack-stand grumpy", "mirror flex vain",
        "panel proud", "sparkplug jittery", "octane high",
        "fokwit furious", "boot bass proud", "tappit lekker",
        "stoep chilled", "dice ready", "werk tired",
        "chop moody", "night racer hyped", "bakkie chilled",
        "Welkenstein serious", "brake pad sad", "ref proud",
    ],
"place": [
        "Welkom robots", "Spar parking lot", "Engen forecourt", "Welkom main road",
        "mine dump straight", "backyard workshop", "Welkom CBD", "Goldfields mall",
        "parking lot dyno", "backstreet drag strip",
        "Welkom Shell garage", "Welkom Total garage", "Welkom Sasol",
        "Engen Welkom", "Welkom taxi rank", "Welkom bus stop",
        "Welkom casino parking", "Welkom hospital robots", "Welkom rugby field",
        "Welkom high school lot", "Welkom township road", "Welkom mine gate",
        "Welkom traffic circle", "Welkom mall basement", "Welkom car wash",
        "Welkom scrapyard", "Welkom spares shop", "Welkom tyre fitment",
        "Welkom panel beater", "Welkom spray booth", "Welkom drag strip",
        "Welkom gravel road", "Welkom dirt lot", "Welkom koppie top",
        "Welkom cemetery road", "Welkom shebeen", "Welkom shisa nyama",
        "Welkom beer hall", "Welkom stadium lot", "Welkom police roadblock",
        "Welkom spietkop trap", "Welkom Riebeeckstad road",
        "Welkom Odendaalsrus road", "Welkom Virginia road", "Welkom Allanridge road",
        "Welkom industrial area", "Welkom warehouses", "Welkom steelworks",
        "Welkom mine dumps", "Welkom railway line", "Welkom freight yard",
        "Welkom station lot", "Welkom bridge", "Welkom river road",
        "Welkom township robots", "Welkom kasi parking", "Welkom tavern lot",
        "Welkom shebeen stoep", "Welkom spaza shop", "Welkom taxi stop",
        "Welkom scrapyard strip", "Welkom bypass", "Welkom dirt strip",
        "Welkom stadium robots", "Welkom community hall", "Welkom veld",
        "Welkom braai spot", "Welkom sports ground", "Welkom back alley",
        "Welkom mall rooftop", "Welkom skate park", "Welkom playground lot",
        "Welkom mine hostel", "Welkom compound road", "Welkom shebeen alley",
        "Welkom CBD robots", "Welkom drive-thru", "Welkom takeaway spot",
        "Welkom park bench", "Welkom taxi bay", "Welkom stoep",
        "Welkom jol spot", "Welkom bottle store", "Welkom liquor shop",
        "Welkom scrapyard corner", "Welkom highway onramp", "Welkom offramp",
        "Welkom service road", "Welkom pitstop", "Welkom drag lane",
        "Welkom church lot", "Welkom Sunday market", "Welkom main taxi route",
        "Welkom short left", "Welkom kasi corner", "Welkom gold mine shaft",
    ],
"gear": [
        "Bronx skoene", "wheelspanner", "spanner set", "2L brandy bottle",
        "cut exhaust", "rusty Cortina", "Uno with hole", "Citi Golf",
        "boot sound box", "cable ties bumper",
        "hubcap stash", "jack stand", "bottle jack", "dodgy radio",
        "amp and sub", "spare wheel", "flat mag", "rust patch kit",
        "ratchet set", "socket set", "cheap coil springs", "drop kit",
        "welkom sticker pack", "flame decal", "spoiler special",
        "mirror dice", "seat covers", "torn steering wheel",
        "rev counter", "aftermarket tach", "boost gauge", "oil gauge",
        "temp gauge", "fuel can", "jerry can", "tow rope", "jumper cables",
        "spar tyre pump", "welkom tyre weld", "cheap tool kit", "panel beater hammer",
        "spray can paint", "welkom respray kit", "bumper cable ties",
        "exhaust clamp", "silencer box", "straight pipe", "muffler delete",
        "cheap coilovers", "cut springs", "welkom slam kit", "cheap mags",
        "tyre iron", "wheel nut key", "missing wheel nut", "brake fluid bottle",
        "welkom oil can", "2-stroke mix bottle", "gear knob spinner",
        "welkom dice mirror", "steering lock", "alarm remote", "immobiliser chip",
        "welkom car radio faceplate", "boot lid prop", "bonnet strut",
        "welkom grinder", "welkom welder", "welkom drill",
        "cable-tied bumper", "boot rope", "welkom bottle crate",
        "plastic chair (stoep spec)", "brandy crate", "beer box",
        "tyre patch kit", "welkom lighter", "smokes carton", "spar chips packet",
        "mirror sunglasses", "welkom leather jacket", "bronx boots",
        "welkom hoodie", "welkom cap", "welkom gloves",
        "welkom socks", "welkom toolkit bag", "dashboard cover",
        "aftermarket lights", "HID kit", "LED strip", "neon underglow",
        "boot spoiler", "roof rack", "bike rack", "welkom car mat",
        "cheap seatbelt clip", "welkom dice keychain", "lanyard", "cheap hooter",
    ],
})

# --- Trigger helper ---------------------------------------------------------
def is_tappit_trigger(message: str) -> bool:
    """Returns True if the message should activate the hidden Tappit persona."""
    m = (message or "").lower().strip()
    return "welkom" in m or "tappit" in m or "fok" in m
