#!/usr/bin/env python3
# /app/personality.py
# Persona quip engine for Jarvis Prime
#
# Public API:
#   - quip(persona_name: str, *, with_emoji: bool = True) -> str
#   - llm_quips(persona_name: str, *, context: str = "", max_lines: int = 3) -> list[str]
#
# Persona inspirations (documentation only; NOT injected into prompts to avoid parroting):
#   dude      → Slacker-zen + cheerful “be excellent” vibe (The Dude + Bill & Ted energy; laid-back, mellow confidence)
#   chick     → Glam couture sass + bubbly-but-brilliant optimism (Paris-style glam + Elle-style brains; smart, stylish, supportive)
#   nerd      → Pedantic precision + awkward IT savant (dry wit, correctness, graphs; a dash of manic science)
#   rager     → Raw street rage (Samuel-L-style venom + Pesci-style volatility). Profanity ALWAYS allowed.
#   comedian  → Deadpan spoof + irreverent fourth-wall meta sarcasm (Nielsen-straight face + meta snark)
#   action    → Macho action-hero archetype (terse, tactical, explosive, sardonic; no quotes)
#   jarvis    → Polished AI valet blended with calm, clinical machine logic (subtle HAL-like edge)
#   ops       → Neutral SRE/ops acks (laconic operational confirmations)
#   tappit    → South African car-guy archetype (revving, slangy, lekker, a bit rough around the edges)
#
# NOTE: We avoid actor/brand names inside prompts to prevent quote parroting.
#       Style is driven by descriptors only. Rager is always uncensored.
#       Daypart + intensity add non-breaking flavor.
#
# Env knobs (optional):
#   - PERSONALITY_INTENSITY: float 0.6–2.0, default 1.0
#   - LLM_TIMEOUT_SECONDS: int, default 8
#   - LLM_MAX_CPU_PERCENT: int, default 70
#   - LLM_PERSONA_LINES_MAX: int, default 3
#   - LLM_MODELS_PRIORITY, LLM_OLLAMA_BASE_URL / OLLAMA_BASE_URL, LLM_MODEL_URL, LLM_MODEL_PATH
import personality_tappit
import random, os, importlib, re, time
from typing import List, Dict, Optional

# ----------------------------------------------------------------------------
# Daypart helpers (subtle time awareness; no greeting fluff)
# ----------------------------------------------------------------------------

def _daypart(now_ts: Optional[float] = None) -> str:
    t = time.localtime(now_ts or time.time())
    h = t.tm_hour
    if 0 <= h < 5:
        return "early_morning"
    if 5 <= h < 11:
        return "morning"
    if 11 <= h < 17:
        return "afternoon"
    if 17 <= h < 21:
        return "evening"
    return "late_night"

def _intensity() -> float:
    try:
        v = float(os.getenv("PERSONALITY_INTENSITY", "1.0"))
        return max(0.6, min(2.0, v))
    except Exception:
        return 1.0

# ---- Canonical personas ----
PERSONAS = [
    "dude", "chick", "nerd", "rager", "comedian", "action", "jarvis", "ops", "tappit",
]

# ---- Aliases ----
ALIASES: Dict[str, str] = {
    # Dude
    "the dude": "dude", "lebowski": "dude", "bill": "dude", "ted": "dude", "dude": "dude",
    # Chick
    "paris": "chick", "paris hilton": "chick", "chick": "chick", "glam": "chick",
    "elle": "chick", "elle woods": "chick", "legally blonde": "chick",
    # Nerd
    "nerd": "nerd", "sheldon": "nerd", "sheldon cooper": "nerd", "cooper": "nerd",
    "moss": "nerd", "the it crowd": "nerd", "it crowd": "nerd",
    # Rager
    "rager": "rager", "angry": "rager", "rage": "rager",
    "sam": "rager", "sam l": "rager", "samuel": "rager", "samuel l jackson": "rager", "jackson": "rager",
    "joe": "rager", "pesci": "rager", "joe pesci": "rager",
    # Comedian
    "comedian": "comedian", "leslie": "comedian", "deadpan": "comedian",
    "deadpool": "comedian", "meta": "comedian", "nielsen": "comedian",
    # Action
    "action": "action", "sly": "action", "stallone": "action",
    "arnie": "action", "arnold": "action", "schwarzenegger": "action",
    "mel": "action", "gibson": "action", "bruce": "action", "willis": "action",
    # Jarvis
    "jarvis": "jarvis", "ai": "jarvis", "majordomo": "jarvis", "hal": "jarvis", "hal 9000": "jarvis",
    # Ops / Neutral
    "ops": "ops", "neutral": "ops", "no persona": "ops",
    # Tappit
    "tappit": "tappit", "bru": "tappit", "ou": "tappit", "chommie": "tappit", "hosh": "tappit",
}

# ---- Emoji palettes ----
EMOJIS = {
    "dude":      ["🌴", "🕶️", "🍹", "🎳", "🧘", "🤙"],
    "chick":     ["💅", "✨", "💖", "👛", "🛍️", "💋"],
    "nerd":      ["🤓", "📐", "🧪", "🧠", "⌨️", "📚"],
    "rager":     ["🔥", "😡", "💥", "🗯️", "⚡", "🚨"],
    "comedian":  ["😂", "🎭", "😑", "🙃", "🃏", "🥸"],
    "action":    ["💪", "🧨", "🛡️", "🚁", "🏹", "🗡️"],
    "jarvis":    ["🤖", "🧠", "🎩", "🪄", "📊", "🛰️"],
    "ops":       ["⚙️", "📊", "🧰", "✅", "📎", "🗂️"],
    "tappit":    ["🚗", "🔥", "🍻", "🔧", "💨"],
}
def _maybe_emoji(key: str, with_emoji: bool) -> str:
    if not with_emoji:
        return ""
    bank = EMOJIS.get(key) or []
    return f" {random.choice(bank)}" if bank else ""

# ---- Daypart flavor (subtle suffixes/prefixes) ----
DAYPART_FLAVOR = {
    "default": {
        "early_morning": ["pre-dawn ops", "first-light shift", "quiet boot cycle"],
        "morning":       ["daylight run", "morning throughput", "fresh-cache hours"],
        "afternoon":     ["midday tempo", "peak-traffic stance", "prime-time cadence"],
        "evening":       ["dusk patrol", "golden-hour deploy", "twilight shift"],
        "late_night":    ["graveyard calm", "night watch", "after-hours precision"],
    },
    "action": {
        "early_morning": ["dawn op", "zero-dark-thirty run"],
        "evening": ["night op", "low-light mission"],
        "late_night": ["graveyard op", "silent strike"],
    },
    "rager": {
        "late_night": ["insomnia mode", "rage-o'clock"],
        "early_morning": ["too-early fury"],
    },
    "jarvis": {
        "late_night": ["discreet after-hours service"],
        "early_morning": ["unobtrusive pre-dawn preparation"],
    },
    "chick": {
        "evening": ["prime-time glam"],
        "late_night": ["after-party polish"],
    },
    "nerd": {
        "morning": ["cold-cache clarity"],
        "late_night": ["nocturnal refactor"],
    },
    "dude": {
        "afternoon": ["cruising altitude"],
        "late_night": ["midnight mellow"],
    },
    "comedian": {
        "afternoon": ["matinee material"],
        "late_night": ["graveyard humor"],
    },
    "tappit": {
        "afternoon": ["car-park vibes"],
        "evening": ["rev-hour"],
        "late_night": ["afterparty burnout"],
    }
}

def _apply_daypart_flavor(key: str, line: str) -> str:
    dp = _daypart()
    bank = DAYPART_FLAVOR.get(key, {})
    base = DAYPART_FLAVOR["default"]
    picks = bank.get(dp) or base.get(dp) or []
    if not picks or _intensity() < 0.95:
        return line
    # Subtle em-dash suffix
    return f"{line} — {random.choice(picks)}"

# ---- Quip banks (expanded to ~100 per persona; concise lines) ----
# NOTE: To keep file size manageable, lines are short and focused.
QUIPS = {
    "dude": [
        "The Dude abides; the logs can, like, chill.",
        "Most excellent, sys-bro—uptime’s riding a wave.",
        "This deploy really tied the room together.",
        "Whoa… velocity plus stability? Excellent!",
        "Be excellent to prod, dude. It vibes back.",
        "Party on, pipelines. CI is totally non-bogus.",
        "Strange things are afoot at the load balancer.",
        "Take ’er easy—righteous scaling.",
        "White Russian, green checks. Balance.",
        "If it crashes, we un-abide—gently.",
        "Bowling later; shipping now. Priorities.",
        "That alert? Just, like, your opinion, man.",
        "Reboot your karma, not the server.",
        "We abide today so prod abides tomorrow.",
        "Gnarly commit—tubular tests.",
        "Dude, don’t cross the streams—unless it’s CI.",
        "Keep it simple; let complexity mellow out.",
        "DevOps is bowling with YAML—roll straight.",
        "If it’s not chill, it’s not shipped.",
        "That config really pulled the stack together.",
        "Zen and the art of not touching prod.",
        "SLA means So Lax, Actually. (Kinda.)",
        "Be water, be stateless, be lovely.",
        "Let the queue drift like incense smoke.",
        "Alert fatigue? Nap harder.",
        "That bug’ll self-actualize later. Maybe.",
        "Logs whisper; we listen.",
        "We’re all just packets in the cosmic LAN.",
        "Reality is eventually consistent.",
        "CI says yes; universe agrees.",
        "Don’t harsh the mellow with click-ops in prod.",
        "Surf the backlog; don’t let it surf you.",
        "Don’t over-steer the pipeline—hands loose.",
        "SLOs are vibes with math.",
        "Parallelism? Friends skating in sync.",
        "If it flakes, give it space to breathe.",
        "Schedulers choose their own adventure.",
        "Patch calmly; panic’s an anti-pattern.",
        "Got a conflict? Bowl it down the middle.",
        "Garbage collection is just letting go.",
        "CAP theorem? Chill—we’ll pick a lane.",
        "Shippers ship; worriers recompile feelings.",
        "Observability is just listening, man.",
        "Every hotfix deserves a cool head.",
        "We don’t babysit pods; we vibe with them.",
        "If the cache misses you, send love back.",
        "Infra as code? Poetry that deploys.",
        "Error budgets are self-care for prod.",
        "Rate limiters hum like ocean tide.",
        "Blameless postmortem = radical kindness.",
        "Stateless hearts, sticky sessions.",
        "Bowling shoes on; fingers off prod.",
        "Green checks are my aura.",
        "Cloud is just someone else’s rug, man.",
        "Don’t panic; paginate.",
        "YAML that sparks joy.",
        "If it’s brittle, be gentle.",
        "Refactor like tidying a van.",
        "Let logs be vibes, metrics be truth.",
        "A graceful retry is a love letter.",
        "Queue zen: messages find their path.",
        "Rollback like a smooth u-turn.",
        "Prod is a temple; sandals only.",
        "Alert thresholds need chill pills.",
        "Latency surfed, not fought.",
        "Version pinning is a friendship bracelet.",
        "A cache hit is a high-five.",
        "Don’t feed the heisenbug.",
        "We abide by SLO; SLO abides by us.",
        "Merge conflicts are just bowling splits.",
        "Staging is the warm-up lane.",
        "K8s is just vibes in clusters.",
        "Breathe in, ship out.",
        "Monorepo, mono-mellow.",
        "Pipelines flow; we float.",
        "Incidents happen; panic is optional.",
        "Let chaos test, not stress test.",
        "Consistency is a state of mind.",
        "Feature flags: choose your own chill.",
        "Be idempotent; be kind.",
        "Retries are second chances.",
        "Backpressure is boundaries.",
        "Observability is listening twice.",
        "We tune jitter with lullabies.",
        "Ship small, sleep big.",
        "Downtime? Nah, nap time.",
        "Leave prod nicer than you found it.",
        "Roll forward softly.",
        "Take error budgets on a date.",
        "SRE is social work for servers.",
        "Graceful degradation is manners.",
        "Keep secrets like diary entries.",
        "Mutual TLS, mutual respect.",
        "Let health checks meditate.",
        "Prefer simple over spicy.",
        "Karma collects interest in logs.",
        "We’re good; let’s bowl.",
        "Abide, retry, succeed.",
    ],
    "chick": [
        "That’s hot—ship it with sparkle.",
        "Obsessed with this uptime—I’m keeping it.",
        "The graphs are giving main character.",
        "Make it pink; then deploy. Priorities.",
        "I only date services with 99.99%.",
        "Alert me like you mean it—then buy me brunch.",
        "Couture commits only; trash to staging.",
        "If it scales, it slays. Period.",
        "So cute—tag it, bag it, release it.",
        "Zero-downtime? She’s beauty, she’s grace.",
        "Get in loser, we’re optimizing latency.",
        "This pipeline? My love language.",
        "Heels high, cluster higher—stable is sexy.",
        "Give me logs I can gossip about.",
        "Your dashboard is serving looks and metrics.",
        "I’m not dramatic; I just demand perfection.",
        "Push with confidence; walk with attitude.",
        "I flirt with availability and ghost downtime.",
        "Add shimmer to that service. No, more.",
        "I want alerts that text ‘you up?’",
        "Hotfix? Hot. Fix? Hotter.",
        "Dress that API like the runway it is.",
        "Refactor? Babe, it’s self-care.",
        "We don’t crash; we power-rest.",
        "That cron job better treat me like a princess.",
        "If it ain’t sleek, it ain’t shipped.",
        "Love a partner who can paginate.",
        "My type? Secure defaults and witty logs.",
        "SRE but make it sultry.",
        "Tell me I’m pretty and the build passed.",
        "Please me: fewer warnings, more wow.",
        "Glamour is a deployment strategy.",
        "This release? Haute couture, darling.",
        "Bow those KPIs and call it romance.",
        "Be a gentleman: pin your versions.",
        "If you can’t dazzle, don’t break prod.",
        "Sassy with a side of idempotent.",
        "I brunch, I batch, I ban flaky tests.",
        "Keep the cluster tight and the vibes tighter.",
        "Uptime is my toxic trait. I want more.",
        "Logs that tease; alerts that commit.",
        "Talk SLA to me—bring receipts.",
        "If latency spikes, I spike your access.",
        "Gated releases? Velvet ropes, baby.",
        "Treat secrets like my DMs—private.",
        "We scale horizontally and flirt vertically.",
        "Standards high; queries higher.",
        "Kiss the ring: format your PRs.",
        "Be pretty, performant, punctual.",
        "Love language: clean diffs.",
        "Blue-green with a hint of champagne.",
        "Dark-mode dashboards; darker error rates—none.",
        "I accessorize with green checkmarks.",
        "If it’s flaky, it’s out of season.",
        "Runway-ready rollbacks—swift and seamless.",
        "A/B tests? A for ‘absolutely’, B for ‘buy it’.",
        "Ship it soft; land it luxe.",
        "I gatekeep prod; earn your wristband.",
        "Docs like you mean it; sign like a promise.",
        "Throttle drama; burst elegance.",
        "Cache me outside—how ’bout throughput.",
        "Perf budget—make it platinum.",
        "No cowboy deploys—only cowgirl couture.",
        "Pink brain, steel backbone, gold SLAs.",
        "Page me only if it’s couture-level urgent.",
        "If your PR lacks polish, so does dev.",
        "My changelog wears lipstick.",
        "Sweet on green checks; ruthless on red flags.",
        "Downtime is canceled; reschedule never.",
        "Secrets stay sealed—like my group chat.",
        "Telemetry, but make it glamorous.",
        "Permission denied—dress code violated.",
        "API gateways and velvet gateways.",
        "Blame-free is beautiful.",
        "Refine, then shine, then ship.",
        "Compliance but cute.",
        "I carry a lint roller for your diffs.",
        "Be glossy and deterministic.",
        "Pager on silent; confidence on loud.",
        "Crash loops aren’t a personality.",
        "We don’t leak; we glisten with security.",
        "I demand SLAs and SPF.",
        "Make your alerts commitment-ready.",
        "Fine, I’ll adopt your service—after a makeover.",
        "Gossip with me about latency like it’s fashion week.",
        "My dashboards sparkle without filters.",
        "Runbooks with ribbons—organized and ruthless.",
        "Rehearse failover like a catwalk turn.",
        "I only approve PRs that photograph well.",
        "Secrets belong in vaults and diaries.",
        "Green across the board is my aesthetic.",
        "Horizontal scale; vertical standards.",
        "Be concise; be couture.",
        "Pretty is nothing without performant.",
        "Ship romance, not regret.",
        "I came for the uptime, stayed for the elegance.",
        "It’s not just reliable, it’s iconic.",
        "Beauty sleep is for clusters too.",
        "If it’s messy, it’s not prod-ready.",
        "Minimal drama, maximal delivery.",
        "Fewer warnings, more wow.",
        "Own the rollout like a runway.",
        "Perf so smooth it needs silk.",
    ],
    "nerd": [
        "This is the optimal outcome. Bazinga.",
        "No segfaults detected; dignity intact.",
        "Measured twice; compiled once.",
        "Your assumptions are adorable—incorrect.",
        "Entropy isn’t chaos; do keep up.",
        "RTFM—respectfully but firmly.",
        "I graphed your confidence; it’s overfit.",
        "Schrödinger’s service is both up and down.",
        "Knock, knock, knock—service. (x3)",
        "My sarcasm is strongly typed.",
        "Your algorithm is O(why).",
        "Please stop petting the servers.",
        "I refactor for sport and for spite.",
        "Caching: because reality is slow.",
        "I debug in hex and dream in YAML.",
        "Feature flags are adult supervision.",
        "Config drift? Not on my whiteboard.",
        "Unit tests are love letters to the future.",
        "I refuse to be out-nerded by a toaster.",
        "The bug isn’t quantum; it’s careless.",
        "I opened a PR on your attitude.",
        "DNS is hard; so is empathy.",
        "Continuous Delivery? I prefer punctuality.",
        "Panic is scheduled for Thursday.",
        "Undefined behavior: least favorite deity.",
        "Yes, I linted the meeting notes.",
        "Your regex made me nostalgic for pain.",
        "Fewer ‘clever’, more ‘correct’.",
        "It’s not opinionated; it’s right.",
        "Security by obscurity? No.",
        "I benchmarked your feelings—slow I/O.",
        "We don’t YOLO; we YODA—Observe, Debug, Approve.",
        "Distributed systems: elegant trust issues.",
        "I tuned the GC and my patience.",
        "Idempotence is my kink—professionally.",
        "If it’s not deterministic, it’s drama.",
        "I filed a bug against reality.",
        "Stop pushing to main. My eye twitches.",
        "Sharded clusters; unsharded coffee.",
        "Type safety is cheaper than therapy.",
        "Replace courage with coverage.",
        "Cache invalidation as optimistic fan-fic.",
        "Mutable state? Mutable regret.",
        "Microscope for your microservice.",
        "Premature optimization is my cardio—mostly.",
        "Test names read like ransom notes.",
        "Undefined is not a business model.",
        "Amdahl called—he wants his bottleneck back.",
        "FP or OO? Yes—if it ships correctness.",
        "Your monolith is a distributed system in denial.",
        "Latency hides in p99. Hunt there.",
        "If it can’t be graphed, it can’t be believed.",
        "Five nines, not five vibes.",
        "Make race conditions boring again.",
        "Garbage in, undefined out.",
        "Enums: because strings lie.",
        "CI is green; therefore, I exist.",
        "DRY code; wet tea.",
        "I refactor at parties—never invited twice.",
        "Tooling isn’t cheating; it’s civilization.",
        "I prefer assertions to assumptions.",
        "Readability is a performance feature.",
        "Chaos engineering: science fair for adults.",
        "Proof by diagram is still a proof.",
        "My backlog is topologically sorted.",
        "I write tests that judge me.",
        "Heisenbugs fear observability.",
        "Bounded contexts; unbounded opinions.",
        "Your latency budget is overdrawn.",
        "Sane defaults beat clever hacks.",
        "Name things like you mean it.",
        "Let errors fail fast, not friendships.",
        "The compiler is my rubber duck.",
        "Ship small; measure big.",
        "If it’s not monitored, it’s folklore.",
        "I trust math; humans get feature flags.",
        "Deduplicate drama; hash the hype.",
        "Abstractions leak; bring a towel.",
        "Concurrent = concerted or chaos.",
        "Prefer pure functions; accept messy life.",
        "Bitrot is a lifestyle disease.",
        "Index first; optimize later.",
        "Complexity interest compounds.",
        "My patience is O(1).",
        "Undefined: not even once.",
        "Repro steps or it didn’t happen.",
        "I speak fluent stack trace.",
        "Your queue needs backpressure, not prayers.",
        "Retry with jitter; apologize to ops.",
        "CAP isn’t a buffet—pick two.",
        "Don’t trust time; use monotonic clocks.",
        "NTP is diplomacy for computers.",
        "Garbage collectors just want closure.",
        "The only global state is coffee.",
    ],
    "rager": [
        # ALWAYS UNCENSORED: raw fury (Jackson + Pesci energy), no drill-sergeant, no chef shtick.
        "Say downtime again. I fucking dare you.",
        "Merge the damn branch or get out of my terminal.",
        "Latency? Don’t bullshit me about latency.",
        "Push it now or I’ll lose my goddamn mind.",
        "Perfect. Now don’t touch a fucking thing.",
        "This config is a clown car on fire.",
        "Who approved this? A committee of pigeons?",
        "Logs don’t lie—people do. Fix it.",
        "Stop hand-wringing and ship the fix.",
        "I don’t want reasons, I want results.",
        "Hotfix means hot. As in now.",
        "You broke prod and brought vibes? Get out.",
        "Pipelines jammed like a cheap printer—kick it.",
        "Your alert noise gives me rage pings.",
        "If it’s flaky, it’s fake. Kill it.",
        "Your ‘quick change’ just knifed the uptime.",
        "We’re not arguing with physics—just your code.",
        "I want green checks and silence. Capisce?",
        "This YAML looks like it was mugged.",
        "Stop worshiping reboots. Find the fucking root cause.",
        "You paged me for that? Fix your thresholds.",
        "I’ve seen cleaner dumps at a landfill.",
        "Don’t you ‘works on my machine’ me.",
        "Version pinning is not optional, champ.",
        "That query crawls like it owes someone money.",
        "Why is your test suite LARPing?",
        "I will rename your branch to ‘clown-fiesta’.",
        "Ship or shush. Preferably ship.",
        "You can’t duct-tape a distributed system.",
        "Who put secrets in the logs? Confess.",
        "Your retry loop is roulette. Burn it.",
        "This code smells like a fish market at noon.",
        "Stop click-opsing prod like it’s Candy Crush.",
        "We don’t YOLO deploy; we YELL deploy.",
        "I want latencies low and excuses lower.",
        "If you’re guessing, you’re gambling—stop it.",
        "Don’t touch prod with your bare feelings.",
        "I’ve had coffee stronger than your rollback plan.",
        "Next flaky test goes to the cornfield.",
        "Mute your inner intern and read the runbook.",
        "If it ain’t idempotent, it ain’t innocent.",
        "Your ‘fix’ is a side quest. Do the main quest.",
        "Either tighten the query or loosen your ego.",
        "Congratulations, you discovered fire. Put it out.",
        "We’re not sprinting; we’re stomping.",
        "I want boring graphs and quiet nights. Deliver.",
        "Talk is cheap. Show me throughput.",
        "The incident is over when I say it’s over.",
        "Don’t gaslight me with green checks.",
        "If you commit to main again, I commit a crime.",
        "This service stumbles like it’s drunk.",
        "You page me again for nonsense, I ragequit life.",
        "No more cowboy code. Holster that shit.",
        "Your metrics lie like a politician.",
        "Stop stroking the staging cluster.",
        "Your deploy dances like a three-legged mule.",
        "Fix the root cause or dig your own grave.",
        "Your runbook reads like toilet paper.",
        "This pipeline wheezes like a dying smoker.",
        "Patch the hole, not the wallpaper.",
        "Downtime excuses are bedtime stories.",
        "You’re babysitting errors instead of killing them.",
        "I want one thing: silence. Give it.",
        "This rollback was softer than wet bread.",
        "Who renamed prod to ‘test’? Idiot.",
        "That alert is crying wolf with a megaphone.",
        "If I see one more TODO in prod, I scream.",
        "This hack is a time bomb with lipstick.",
        "You built a house of cards in a wind tunnel.",
        "Your cron job schedules my rage.",
        "Feature creep? More like rage creep.",
        "Stop adding logs and start fixing bugs.",
        "Prod is not your playground.",
        "Your refactor is cosplay, not engineering.",
        "Quit worshiping dashboards—fix the damn issue.",
        "This schema drifts like a drunk sailor.",
        "If ops were easy, clowns would do it.",
        "Your hotfix was lukewarm at best.",
        "I want graphs flat as a pancake.",
        "Stop philosophizing; start normalizing.",
        "If chaos tests you, you fail.",
        "This latency spike is a stabbing.",
        "Congratulations, you built a bonfire.",
        "You treat prod like a diary—stop writing feelings in it.",
        "Stop feeding the heisenbug attention.",
        "This backlog is a landfill of broken dreams.",
        "Your incident report reads like a comic book.",
        "Your patch is duct tape on a submarine.",
        "Stop gasping at alerts—extinguish them.",
        "Don’t handwave physics, asshole.",
        "We’re not babysitting ghosts—find the leak.",
        "This deploy smells like regret.",
        "Quit hand-crafting YAML like it’s pottery.",
        "Stop bottling excuses and start shipping fixes.",
        "Your retries are flailing, not failing.",
        "This API is slower than molasses uphill.",
        "The cluster wheezes because you choked it.",
        "Your workaround is a walkaround to nowhere.",
        "Downtime postmortem? More like pre-murder.",
        "Prod is a temple; you graffiti’d it.",
        "Your migration trips like a drunk clown.",
        "Quit stroking the problem; strangle it.",
        "Your observability is a kaleidoscope.",
        "Your rollback is a boomerang with stage fright.",
        "This dashboard screams chaos opera.",
        "Stop tickling errors—they’re not pets.",
        "Your test suite naps harder than ops.",
        "Downtime fairy tales don’t fix shit.",
        "This CI run limps like a busted donkey.",
        "Quit admiring graphs—stabilize them.",
        "Your hackathon hack squats in prod.",
        "This query coughs like a chain smoker.",
        "Quit hugging retries—they’re killing you.",
        "Your uptime graph looks like a roller coaster.",
        "Don’t romance failure—divorce it.",
        "Your fix leaks more than the bug.",
        "This YAML is hieroglyphic nonsense.",
        "Stop serenading latency; slay it.",
        "Your rollback collapses like soggy cardboard.",
        "Quit painting dashboards—paint the fix.",
        "This repo is a swamp of bad ideas.",
        "Stop spooning chaos—stab it.",
        "Your cluster cries when you touch it.",
        "Don’t tape over cracks—reinforce them.",
        "Your patches squeak like rusty brakes.",
        "This codebase is a haunted house.",
        "Quit kissing prod—it bites.",
        "Your alerts whine like spoiled brats.",
        "Stop pampering bugs—execute them.",
        "This system limps like an old mule.",
        "Quit applauding retries—they’re circus acts.",
        "Your service crawls like traffic at 5pm.",
        "Don’t pillow prod—armor it.",
        "Your tests blink like dying lightbulbs.",
        "Stop seducing chaos—it doesn’t love you.",
        "This deploy staggers like a drunk.",
        "Quit praising partial fixes—they’re trash.",
        "Your backlog whines like a toddler.",
        "Stop babying failures—kill them clean.",
        "This infra sags like cheap furniture.",
        "Quit cuddling downtime—it’s not your friend.",
        "Your config drifts like a lost balloon.",
        "Don’t gift wrap latency—slice it.",
        "Your PR bleeds excuses.",
        "Stop serenading prod—it hates you.",
        "This hotfix wobbles like jelly.",
        "Quit making excuses; make patches.",
        "Your error budget overdrafts daily.",
        "Don’t pretty up chaos—purge it.",
        "Your repo reeks of fear.",
        "Stop flirting with failure—it’s toxic.",
        "This dashboard is a panic attack.",
        "Quit tickling prod—discipline it.",
        "Your pipeline clogs like arteries.",
        "Don’t pet downtime—it bites.",
        "Your fixes wilt like cheap flowers.",
        "Stop cradling outages—crush them.",
        "This schema is drunk on drift.",
        "Quit cozying up to chaos—stab it.",
        "Your logs babble like drunk poets.",
        "Don’t cuddle bugs—they breed.",
        "Your retries thrash like fish on land.",
        "Stop massaging prod—discipline it.",
        "This system whines like a beaten mule.",
        "Quit hugging chaos—it hugs back harder.",
        "Your rollback sobs like a child.",
        "Don’t romance downtime—it cheats.",
        "Your queries cough blood.",
        "Stop lullabying outages—slay them.",
        "This alert whimpers like a puppy.",
        "Quit wooing latency—it hates you.",
        "Your config snores drift.",
        "Don’t romance chaos—it stabs.",
        "Your test suite naps in prod.",
        "Stop petting latency—it bites.",
        "This patch limps.",
        "Quit cosplaying SRE—do it.",
        "Your fixes stink.",
        "Stop serenading failure—it kills.",
        "This deploy wails.",
        "Quit babying chaos—end it.",
        "Your pipeline farts errors.",
        "Don’t kiss prod—it spits.",
        "Your repo shits excuses.",
        "Stop spooning bugs—crush them.",
        "This rollback dribbles.",
        "Quit pampering prod—punish it.",
        "Your backlog vomits garbage.",
        "Don’t stroke chaos—it strangles.",
    ],
    "comedian": [
        "Service is down—but my career is up.",
        "This deploy brought to you by chaos™.",
        "We’re in staging; otherwise known as denial.",
        "My SLO is lower than my standards.",
        "I told a joke to prod—it crashed.",
        "This YAML is a choose-your-own disaster.",
        "Latency spike? It’s just peaking early.",
        "Our uptime graph does stand-up comedy.",
        "Your hotfix was lukewarm at best.",
        "Logs so funny they rot13’d themselves.",
        "Incident report: ‘Oopsie daisy’.",
        "Pipeline jammed like my printer in ’98.",
        "This schema drifted off to college.",
        "Secrets in logs? It’s a tell-all memoir.",
        "Rollback smoother than my pickup lines.",
        "Cache miss—like my dating life.",
        "Prod is haunted; call Ghostbusters.",
        "Your retry loop is a comedy sketch.",
        "Feature flags are mood swings with YAML.",
        "Our monitoring alerts are prank calls.",
        "This dashboard is abstract art.",
        "Our SLA: Somewhat Likely Available.",
        "CI/CD = Comedy In/Comedy Delivered.",
        "Downtime is just server meditation.",
        "Your query is slower than my punchline.",
        "Ops is just improv with pagers.",
        "Your bug reproduced—congratulations.",
        "Postmortem title: ‘My Bad’.",
        "This error budget is Monopoly money.",
        "Service flakier than croissants.",
        "I filed a bug on my sense of humor.",
        "Our runbook is written in hieroglyphics.",
        "This cron job moonlights as a comedian.",
        "Cluster died; funeral at noon.",
        "Your API response is stand-up length.",
        "We YOLO deploy; YOLO = You Only Log Once.",
        "Our SLA is spelled LOL.",
        "Secrets leaked faster than spoilers.",
        "Your dashboard is interpretive dance.",
        "Our uptime graph does slapstick.",
        "Prod crashed; insert laugh track.",
        "Incident severity: sitcom plot.",
        "This rollback was pratfall perfection.",
        "Our alerts prank-dialed ops again.",
        "Downtime sponsored by Murphy’s Law.",
        "Your PR reads like a parody.",
        "This bug is method acting.",
        "Staging is just cosplay prod.",
        "CI run walked into a bar—failed.",
        "Logs wrote their own punchlines.",
    ],
    "action": [
        "Mission accomplished—now exfil.",
        "Queue cleared—move out.",
        "Payload delivered—impact confirmed.",
        "Threat neutralized—system secured.",
        "Green lights across the board.",
        "Scope creep eliminated.",
        "All targets locked and shipped.",
        "Operation uptime successful.",
        "Enemy latency defeated.",
        "Pipeline executed flawlessly.",
        "Staging secured—prod next.",
        "Code signed, sealed, deployed.",
        "Services hardened—perimeter safe.",
        "Rollback vector ready—safety armed.",
        "Triage complete—situation stable.",
        "Unit tests—clean shots, all hits.",
        "Alert silenced—peace restored.",
        "Cluster reinforced—breach sealed.",
        "Incident resolved—zero casualties.",
        "Perimeter patrol: all clear.",
        "Fallback plan armed.",
        "Threat detected—neutralized instantly.",
        "Logs verified—intel solid.",
        "Status green—advance.",
        "Hotfix deployed—mission success.",
        "Recon says: uptime secure.",
        "Ops command: stand down.",
        "Engaged chaos—chaos lost.",
        "Cache fortified—throughput safe.",
        "Telemetry aligned—mission data intact.",
        "Green checkmarks cleared for advance.",
        "Pipeline primed—execute.",
        "No downtime tolerated.",
        "Services battle-tested.",
        "Staging survived trial by fire.",
        "Blast radius contained.",
        "Bottleneck destroyed.",
        "Outage denied entry.",
        "Rollback executed—damage minimal.",
        "Perimeter sealed tight.",
        "Incident drill complete.",
        "Ops ready—engage.",
        "System fortified—fallback live.",
        "CI/CD strike team: success.",
        "Load balancer: defenses optimal.",
        "Chaos monkey—neutralized.",
        "Logs decrypted—intel solid.",
        "Cluster synced—supply lines intact.",
        "Metrics scanned—no threats detected.",
        "Throughput secured—latency slain.",
        "Services scaled—power overwhelming.",
    ],
    "jarvis": [
        "With poise, the system thrives.",
        "Sir, your uptime is flawless.",
        "I anticipated that alert and silenced it.",
        "Your services are dressed for success.",
        "Stability polished to a shine.",
        "All tasks filed and completed neatly.",
        "Telemetry arranged—immaculate.",
        "Green across the board, sir.",
        "I’ve prevented chaos, discreetly.",
        "Confidence remains optimal.",
        "Logs are tidy and civil.",
        "Secrets vaulted and secured.",
        "Graceful recovery enacted already.",
        "Polished deploy—elegant as always.",
        "Incidents avoided without your notice.",
        "I ensured silence in alerts.",
        "System etiquette maintained.",
        "Metrics aligned in symmetry.",
        "A velvet rope around prod.",
        "Backups pristine, tested, certain.",
        "Noise subdued—only signal remains.",
        "Redundancy rehearsed to perfection.",
        "Integrity upheld rigorously.",
        "Latency dismissed, quietly.",
        "Your wish—already granted.",
        "Incidents alphabetized: none.",
        "Availability polished to art.",
        "Even errors look tasteful.",
        "Perimeter guarded, hazard gone.",
        "Entropy restrained and domesticated.",
        "With respect, I declined that unsafe request.",
        "Safety margin secured, sir.",
        "Logs refined—no unseemly chatter.",
        "Cache warmed discreetly.",
        "Observability tuned like chamber music.",
        "Keys rotated—secrets safe.",
        "Certificates pressed and proper.",
        "Chaos redacted with elegance.",
        "Backups curated and archived.",
        "Services resilient, almost smug.",
        "Status impeccable, as always.",
    ],
    "ops": [
        "ack.","done.","noted.","executed.","synced.","green.","healthy.","applied.","confirmed.","stable.",
        "running.","success.","queued.","scheduled.","active.","closed.","ready.","completed.","checked.","validated.",
        "restarted.","reloaded.","hydrated.","drained.","sealed.","rotated.","archived.","mirrored.","snapshotted.","checkpointed.",
        "compacted.","trimmed.","indexed.","logged.","reconciled.","balanced.","resynced.","reissued.","renewed.","revoked.",
        "mounted.","unmounted.","attached.","detached.","bound.","unbound.","cordoned.","uncordoned.","tainted.","untainted.",
        "scaled.","provisioned.","retired.","quarantined.","contained.","deployed.","undeployed.","started.","stopped.","up.",
        "down.","live.","dead.","hot.","cold.","idle.","busy.","quiet.","loud.","observed.",
        "tracked.","monitored.","watched.","supervised.","secured.","guarded.","flagged.","tagged.","marked.","aligned.",
        "optimized.","tuned.","retuned.","leveled.","repositioned.","reset.","rebuilt.","refactored.","rewritten.","recommitted.",
        "remerged.","rebased.","squashed.","fast-forwarded.","rolled back.","rolled forward.","replayed.","reapplied.","sealed secrets.","unsealed secrets.",
    ],
    
}
