{
  "name": "Addons Updater Enhanced",
  "version": "2.2.0",
  "slug": "addons_updater_enhanced",
  "description": "GitHub/Gitea updater with optional Gotify notifications",
  "url": "https://github.com/your-repo/addons_updater_enhanced",
  "arch": ["aarch64", "amd64", "armhf", "armv7", "i386"],
  "startup": "once",
  "boot": "manual",
  "options": {
    "repo_source": {
      "type": "list",
      "options": ["github", "gitea"],
      "required": true,
      "default": "github"
    },
    "enable_gotify": {
      "type": "boolean",
      "default": false
    },
    "gotify_url": {
      "type": "string",
      "required": false
    },
    "gotify_token": {
      "type": "string",
      "required": false
    },
    "gitea_api_url": {
      "type": "string",
      "required": false
    },
    "gitea_token": {
      "type": "string",
      "required": false
    },
    "repo_path": "/config/addons",
    "repo_branch": "main",
    "addon_paths": ["addons", "community-addons"],
    "update_mode": {
      "type": "list",
      "options": ["commit", "push"],
      "default": "commit"
    }
  },
  "schema": {
    "repo_source": "list(github|gitea)",
    "enable_gotify": "bool?",
    "gotify_url": "str?",
    "gotify_token": "str?",
    "gitea_api_url": "str?",
    "gitea_token": "str?",
    "repo_path": "str",
    "repo_branch": "str",
    "addon_paths": ["str"],
    "update_mode": "list(commit|push)"
  }
}
