{
  "name": "Addons Updater Enhanced",
  "version": "3.0.0",
  "slug": "addons_updater_enhanced",
  "description": "GitHub/Gitea updater with optional Gotify",
  "url": "https://github.com/your-repo/addons_updater_enhanced",
  "arch": ["aarch64", "amd64", "armhf", "armv7", "i386"],
  "startup": "application",
  "boot": "manual",
  "hassio_api": true,
  "hassio_role": "manager",
  "map": ["config:rw", "backup:rw"],
  "options": {
    "repo_source": "github",
    "enable_gotify": false,
    "gotify_url": null,
    "gotify_token": null,
    "gitea_api_url": null,
    "gitea_token": null,
    "repo_path": "/config/addons",
    "repo_branch": "main",
    "addon_paths": ["addons", "community"],
    "update_mode": "commit",
    "timeout": 300
  },
  "schema": {
    "repo_source": {
      "type": "list",
      "options": ["github", "gitea"],
      "required": true
    },
    "enable_gotify": "bool",
    "gotify_url": "str?",
    "gotify_token": "str?",
    "gitea_api_url": "str?",
    "gitea_token": "str?",
    "repo_path": "str",
    "repo_branch": "str",
    "addon_paths": ["str"],
    "update_mode": {
      "type": "list",
      "options": ["commit", "push"]
    },
    "timeout": "int?"
  }
}
