{
  "name": "Addons Updater Enhanced",
  "version": "2.3.0",
  "slug": "addons_updater_enhanced",
  "description": "Enhanced version with GitHub/Gitea choice and optional Gotify",
  "url": "https://github.com/your-repo/addons_updater_enhanced",
  "arch": ["aarch64", "amd64", "armhf", "armv7", "i386"],
  "startup": "once",
  "boot": "manual",
  "hassio_api": true,
  "hassio_role": "manager",
  "map": ["config:rw", "backup:rw"],
  "options": {
    "repo_source": "github",
    "enable_notifications": false,
    "gotify_url": null,
    "gotify_token": null,
    "gitea_api_url": null,
    "gitea_token": null,
    "repo_path": "/config/addons",
    "repo_branch": "main",
    "addon_paths": ["addons", "community-addons"],
    "update_mode": "commit",
    "timeout": 300,
    "log_level": "info"
  },
  "schema": {
    "repo_source": "list(github|gitea)",
    "enable_notifications": "bool?",
    "gotify_url": "str?",
    "gotify_token": "str?",
    "gitea_api_url": "str?",
    "gitea_token": "str?",
    "repo_path": "str",
    "repo_branch": "str",
    "addon_paths": ["str"],
    "update_mode": "list(commit|push)",
    "timeout": "int?",
    "log_level": "list(info|debug|warning|error)?"
  }
}
