---
- name: AegisOps Uptime-lite
  hosts: all
  gather_facts: false

  vars:
    _uptime: "{{ lookup('file', '/share/jarvis_prime/aegisops/uptime_targets.yml') | from_yaml }}"
    checks: "{{ _uptime.checks | default([]) }}"

  tasks:
    - name: collect checks for this host
      set_fact:
        my_checks: "{{ checks }}"

    - name: skip host with no checks
      meta: end_play
      when: my_checks | length == 0

    - name: run checks
      include_tasks: /share/jarvis_prime/aegisops/helpers/_do_check.yml
      vars:
        check_item: "{{ item }}"
      loop: "{{ my_checks }}"
      loop_control:
        loop_var: item

    - name: expose results to callback
      ansible.builtin.set_stats:
        data:
          _results: "{{ _results | default([]) }}"
