---
- name: AegisOps Uptime-lite
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  vars_files:
    - /share/jarvis_prime/aegisops/uptime_targets.yml
  vars:
    default_timeout_s: 5

  tasks:
    - name: collect checks for this host
      ansible.builtin.set_fact:
        host_checks: "{{ (checks | selectattr('target','equalto', inventory_hostname) | list) }}"

    - name: skip host with no checks
      ansible.builtin.meta: end_host
      when: host_checks | length == 0

    - name: run checks
      ansible.builtin.include_tasks: /share/jarvis_prime/aegisops/helpers/_do_check.yml
      loop: "{{ host_checks }}"
      loop_control: { loop_var: _chk }
